'use strict';
// KIT.import.rpgmaker — the RPG Maker MV importer, against the fixture project
// generated by test/fixtures/rpgmaker/make.js (regenerate with
// `node test/fixtures/rpgmaker/make.js`).
const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');
const fs = require('fs');
const KIT = require('./_load.js');
const R = (f) => require(path.join(__dirname, '..', '..', f));
R('js/kit/world/map.js'); R('js/kit/world/entities.js'); R('js/kit/world/world.js'); R('js/kit/systems/index.js');
R('js/kit/import/rpgmaker.js');
const RM = KIT.import.rpgmaker;
const P = KIT.project;

const FIX = path.join(__dirname, '..', 'fixtures', 'rpgmaker');
const DATA_FILES = ['MapInfos.json', 'Map001.json', 'Map002.json', 'Tilesets.json', 'System.json', 'CommonEvents.json', 'Items.json', 'Actors.json'];

function loadFiles() {
  const out = {};
  for (const name of DATA_FILES) out[name] = JSON.parse(fs.readFileSync(path.join(FIX, 'data', name), 'utf8'));
  return out;
}
/** A PNG's size straight out of the IHDR, so the importer sees real sheet dimensions. */
function pngSize(file) {
  const b = fs.readFileSync(file);
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}
/** The caller-supplied resolver of the import contract: 'img/x.png' -> { id, src, w, h }. */
function assetResolver() {
  return (src) => {
    const file = path.join(FIX, src);
    if (!fs.existsSync(file)) return null;
    const { w, h } = pngSize(file);
    return { id: KIT.slug(src.replace(/\.png$/i, '')), src: `fixtures/${src}`, w, h };
  };
}
function runImport(opts) {
  return RM.project(loadFiles(), Object.assign({ asset: assetResolver() }, opts || {}));
}
const errorsOf = (problems) => problems.filter(p => p.severity === 'error');

// ---------------------------------------------------------------------------

test('rpgmaker: detect recognises the project and rejects something else', () => {
  const d = RM.detect(loadFiles());
  assert.equal(d.ok, true);
  assert.equal(d.tool, 'rpgmaker-mv');
  assert.equal(d.dialect, 'MV');
  assert.deepEqual(d.maps, [1, 2]);
  assert.equal(RM.detect({ 'map.tmx': '<map/>' }).ok, false);
  assert.throws(() => RM.project({ nothing: 1 }, {}), /not an RPG Maker project/);
});

test('rpgmaker: maps are named from MapInfos and the region layer lands in regions', () => {
  const r = runImport();
  assert.deepEqual(Object.keys(r.maps).sort(), ['inn', 'willow-town']);
  const m = r.maps['willow-town'];
  assert.equal(m.name, 'Willow Town');
  assert.equal(m.width, 6);
  assert.equal(m.height, 5);
  // data is (z * height + y) * width + x; z5 is the region id. The fixture puts region 3 at (2, 4).
  assert.equal(m.layers.regions[4 * 6 + 2], 3);
  assert.equal(m.layers.regions.filter(v => v !== 0).length, 1);
  assert.equal(m.layers.regions.length, 30);
  // z0 -> ground, z1 -> deco, z2/z3 -> above
  assert.equal(m.layers.ground[0], 'willow:16');
  assert.equal(m.layers.ground[1 * 6 + 2], 'willow:9');
  assert.equal(m.layers.deco[3 * 6 + 1], 'willow:17');
  assert.equal(m.layers.above[5], 'willow:20');
  assert.equal(m.layers.above.filter(Boolean).length, 1, 'the shadow layer (z4) is not a tile layer');
  assert.equal(r.maps.inn.width, 4);
  assert.equal(r.maps.inn.music, 'inn');
});

test('rpgmaker: tile flags come from the tileset flags array', () => {
  const r = runImport();
  const tile = (id) => r.tiles.find(t => t.id === id);
  const wall = tile('willow:16');
  assert.equal(wall.solid, true);
  assert.deepEqual(wall.passage, { n: false, s: false, e: false, w: false });
  const grass = tile('willow:1');
  assert.equal(grass.solid, false);
  assert.deepEqual(grass.passage, { n: true, s: true, e: true, w: true });
  assert.equal(tile('willow:9').terrainTag, 1, 'terrain tag lives in the high bits (flag >> 12)');
  assert.equal(tile('willow:17').bush, true);
  assert.equal(tile('willow:18').counter, true);
  const roof = tile('willow:20');
  assert.equal(roof.props.star, true, '0x10 is [*] no effect on passage — not bush');
  assert.equal(roof.solid, false);
  // and the bits Kit has no field for survive on props, with a note
  const ladder = RM.tileFlags(0x600 | 0x20, 5);
  assert.equal(ladder.props.ladder, true);
  assert.equal(RM.tileFlags(0x600 | 0x100, 5).props.damageFloor, true);
  // 0x80 is "counter" on a B-E tile but "table" on an A2 tile
  assert.equal(RM.tileFlags(0x80, 18).counter, true);
  assert.equal(RM.tileFlags(0x80, 2816).counter, false);
  assert.equal(RM.tileFlags(0x80, 2816).props.table, true);
  // one-way passage: 0x08 blocks up, 0x02 blocks left
  assert.deepEqual(RM.tileFlags(0x600 | 0x08 | 0x02, 5).passage, { n: false, s: true, e: true, w: false });
});

test('rpgmaker: tiles are sliced from the right sheet, autotiles are flattened', () => {
  const r = runImport();
  const tile = (id) => r.tiles.find(t => t.id === id);
  // Willow_B is 128px wide over 16 columns, so a tile is 8px.
  // tileId 9: sx = ((floor(9/128) % 2) * 8 + 9 % 8) * 8 = 8, sy = (floor(9/8) % 16) * 8 = 8
  assert.deepEqual(tile('willow:9').art, { image: 'img-tilesets-willow-b', frame: { x: 8, y: 8, w: 8, h: 8 } });  // the id comes from opts.asset
  assert.deepEqual(tile('willow:16').art.frame, { x: 0, y: 16, w: 8, h: 8 });
  assert.deepEqual(RM.tileRect(128, 8, 8), { x: 64, y: 0, w: 8, h: 8 }, 'ids 128-255 sit in the right half of the sheet');
  // tileId 2816 is the A2 sheet: kind 16, shape 0. tx=0 ty=2 -> bx = 0, by = (2-2)*3 = 0.
  // FLOOR_AUTOTILE_TABLE[0][0] = [2, 4], so the top-left quarter is at (2*4, 4*4) = (8, 16).
  const flowers = tile('willow:2816');
  assert.equal(flowers.art.image, 'img-tilesets-willow-a2');
  assert.deepEqual(flowers.art.frame, { x: 8, y: 16, w: 8, h: 8 });
  assert.match(flowers.note, /Autotile kind 16 shape 0/);
  assert.ok(r.problems.some(p => p.code === 'autotile-flattened' && p.severity === 'info'));
  // kind and shape are always measured from TILE_ID_A1 (2048), whichever A sheet the id is on
  assert.equal(RM.autotileKind(2048 + 48 * 3 + 7), 3);
  assert.equal(RM.autotileShape(2048 + 48 * 3 + 7), 7);
  assert.equal(RM.autotileKind(2816), 16, 'A2 starts at kind 16');
  assert.equal(RM.sheetIndexOf(300), 6, 'C sheet');
  assert.equal(RM.sheetIndexOf(1600), 4, 'A5 sheet');
  assert.equal(RM.sheetIndexOf(0), -1);
});

test('rpgmaker: switch and variable names come from System.json', () => {
  const r = runImport();
  // only the switches and variables the project actually touches are declared
  assert.deepEqual(Object.keys(r.vars).sort(), ['chapter', 'coins', 'sunrise-done']);
  assert.equal(r.vars['sunrise-done'].type, 'bool', 'switch 2 is named "Sunrise Done"');
  assert.equal(r.vars['sunrise-done'].default, false);
  assert.equal(r.vars['sunrise-done'].label, 'Sunrise Done');
  assert.ok(r.vars.coins, 'variable 1 is named "Coins"');
  assert.equal(r.vars.coins.type, 'number');
  assert.equal(r.vars.coins.default, 0);
  // unnamed entries fall back to the numbered form
  const t = RM.nameTable(['', 'Met Bran'], ['', 'Coins']);
  assert.equal(t.switchName(1), 'met-bran');
  assert.equal(t.switchName(9), 'switch-9');
  assert.equal(t.varName(7), 'var-7');
  // a name used twice is ambiguous, so both keep their numbers (and it is reported)
  const dup = RM.nameTable(['', 'Flag', 'Flag'], ['', 'Flag']);
  assert.equal(dup.switchName(1), 'switch-1');
  assert.equal(dup.switchName(2), 'switch-2');
  assert.equal(dup.varName(1), 'var-1');
  assert.deepEqual(dup.collisions, ['flag']);
});

test('rpgmaker: message text codes become Kit text codes', () => {
  const ctx = { varName: (n) => (n === 1 ? 'coins' : `var-${n}`), actorName: (n) => (n === 3 ? 'Pilar' : null) };
  assert.equal(RM.convertText('Hi \\N[1] and \\N[2]!', ctx), 'Hi {p1} and {p2}!');
  assert.equal(RM.convertText('\\N[3] waves.', ctx), 'Pilar waves.');
  assert.equal(RM.convertText('You have \\V[1] coins.', ctx), 'You have {var:coins} coins.');
  assert.equal(RM.convertText('\\C[2]Careful\\C[0] now.', ctx), '{color:red}Careful{/color} now.');
  assert.equal(RM.convertText('\\C[3]unclosed', ctx), '{color:green}unclosed{/color}', 'an open colour closes at the end');
  assert.equal(RM.convertText('Wait\\. then\\| then\\!', ctx), 'Wait{pause:250} then{pause:1000} then{wait}');
  assert.equal(RM.convertText('Got \\I[4] it', ctx), 'Got {icon:icon-4} it');
  assert.equal(RM.convertText('\\{big\\} \\>fast', ctx), '{size:big}big{/size} {fast}fast');
  assert.equal(RM.convertText('a \\\\ b', ctx), 'a \\ b', 'a doubled backslash is a literal one');
  assert.equal(RM.convertText('braces {x} stay', ctx), 'braces {{x}} stay', 'literal braces are escaped for KIT.text');
  const problems = [];
  const bag = { once: (s, c, k, m) => problems.push(c), list: problems };
  assert.equal(RM.convertText('gold \\G and \\^', { problems: bag }), 'gold  and ');
  assert.deepEqual(problems, ['text-code-dropped', 'text-code-dropped']);
});

test('rpgmaker: commands translate, and an unsupported code becomes a comment', () => {
  const list = [
    { code: 101, indent: 0, parameters: ['', 0, 0, 2] },
    { code: 401, indent: 0, parameters: ['Line one'] },
    { code: 401, indent: 0, parameters: ['Line two'] },
    { code: 111, indent: 0, parameters: [1, 1, 0, 3, 1] },                    // if variable 1 >= 3
    { code: 121, indent: 1, parameters: [1, 1, 0] },                          // switch 1 = ON
    { code: 411, indent: 0, parameters: [] },
    { code: 102, indent: 1, parameters: [['Yes', 'No'], 1, 0, 2, 0] },
    { code: 402, indent: 1, parameters: [0, 'Yes'] },
    { code: 126, indent: 2, parameters: [1, 0, 0, 2] },                       // give 2 of item 1
    { code: 0, indent: 2, parameters: [] },
    { code: 402, indent: 1, parameters: [1, 'No'] },
    { code: 115, indent: 2, parameters: [] },
    { code: 0, indent: 2, parameters: [] },
    { code: 404, indent: 1, parameters: [] },
    { code: 412, indent: 0, parameters: [] },
    { code: 205, indent: 0, parameters: [0, { list: [
      { code: 4, parameters: [] }, { code: 2, parameters: [] }, { code: 15, parameters: [30] },
      { code: 25, parameters: [] }, { code: 0, parameters: [] },
    ], repeat: false, skippable: true, wait: true }] },
    { code: 505, indent: 0, parameters: [{ code: 4, parameters: [] }] },
    { code: 505, indent: 0, parameters: [{ code: 2, parameters: [] }] },
    { code: 356, indent: 0, parameters: ['OpenGate west 2'] },
    { code: 0, indent: 0, parameters: [] },
  ];
  const out = RM.commands(list, { switches: ['', 'Met Bran'], variables: ['', 'Coins'], items: { 1: 'honey-bun' } });
  assert.deepEqual(out.commands, [
    { t: 'say', who: '', face: null, text: 'Line one\nLine two', position: 'bottom', bg: 'window' },
    { t: 'if',
      when: { kind: 'var', name: 'coins', op: '>=', value: 3 },
      then: [{ t: 'setVar', name: 'met-bran', op: 'set', value: true }],
      else: [
        { t: 'choice', prompt: '', cancel: 'last', options: [
          { text: 'Yes', when: null, then: [{ t: 'give', item: 'honey-bun', count: 2, notify: false }] },
          { text: 'No', when: null, then: [{ t: 'exit' }] },
        ] },
      ] },
    { t: 'moveRoute', target: 'self', steps: ['up', 'left', 'wait:500', 'faceHero'], wait: true, skipBlocked: true, repeat: false },
    { t: 'comment', text: 'RPG Maker Plugin Command [356] ["OpenGate west 2"]', mvCode: 356, mvParams: '["OpenGate west 2"]' },
  ]);
  assert.deepEqual(out.vars, {
    coins: { type: 'number', default: 0, label: 'Coins', group: 'Variables' },
    'met-bran': { type: 'bool', default: false, label: 'Met Bran', group: 'Switches' },
  });
  assert.equal(out.stats.unsupported, 1);
  assert.ok(out.stats.translated >= 5);
  assert.deepEqual(out.problems.filter(p => p.code === 'unsupported-command').length, 1);
  assert.equal(errorsOf(out.problems).length, 0);
});

test('rpgmaker: the flow, progression and screen codes each map to their Kit command', () => {
  const one = (cmd, ctx) => RM.commands([cmd, { code: 0, indent: 0, parameters: [] }], ctx || {}).commands[0];
  assert.deepEqual(one({ code: 123, indent: 0, parameters: ['B', 0] }), { t: 'setSelf', key: 'b', op: 'set', value: true });
  assert.deepEqual(one({ code: 123, indent: 0, parameters: ['A', 1] }), { t: 'setSelf', key: 'a', op: 'set', value: false });
  assert.deepEqual(one({ code: 122, indent: 0, parameters: [2, 2, 1, 0, 5] }, { variables: ['', 'a', 'Chapter'] }),
    { t: 'setVar', name: 'chapter', op: 'add', value: 5 });
  assert.deepEqual(one({ code: 122, indent: 0, parameters: [1, 1, 0, 2, 1, 6] }, { variables: ['', 'Roll'] }),
    { t: 'setVar', name: 'roll', op: 'random', min: 1, max: 6 });
  assert.deepEqual(one({ code: 124, indent: 0, parameters: [0, 30] }), { t: 'timer', op: 'start', seconds: 30 });
  assert.deepEqual(one({ code: 201, indent: 0, parameters: [0, 2, 3, 4, 4, 0] }, { maps: { 2: 'inn' } }),
    { t: 'transfer', map: 'inn', x: 3, y: 4, dir: 'left', fade: true });
  assert.deepEqual(one({ code: 204, indent: 0, parameters: [4, 3, 4] }), { t: 'scrollMap', dx: -3, dy: 0, speed: 4 });
  assert.deepEqual(one({ code: 213, indent: 0, parameters: [0, 4, true] }), { t: 'balloon', target: 'self', kind: '♥', wait: true });
  assert.deepEqual(one({ code: 214, indent: 0, parameters: [] }), { t: 'erase', target: 'self', persistent: false });
  assert.deepEqual(one({ code: 230, indent: 0, parameters: [90] }), { t: 'wait', ms: 1500 });
  assert.deepEqual(one({ code: 221, indent: 0, parameters: [] }), { t: 'fadeOut', ms: 400, color: '#000000' });
  assert.deepEqual(one({ code: 225, indent: 0, parameters: [5, 5, 60, true] }), { t: 'shake', power: 5, ms: 1000 });
  assert.deepEqual(one({ code: 236, indent: 0, parameters: ['storm', 6, 30, false] }), { t: 'weather', kind: 'rain', power: 6, ms: 500 });
  assert.deepEqual(one({ code: 250, indent: 0, parameters: [{ name: 'Door1', volume: 80, pitch: 100, pan: 0 }] }),
    { t: 'sound', id: 'door1', volume: 0.8 });
  assert.deepEqual(one({ code: 242, indent: 0, parameters: [2] }), { t: 'music', id: null, fade: 2000 });
  assert.deepEqual(one({ code: 314, indent: 0, parameters: [0, 1] }), { t: 'heal', hero: 'all' });
  assert.deepEqual(one({ code: 352, indent: 0, parameters: [] }), { t: 'save', prompt: false, slot: 'autosave' });
  assert.deepEqual(one({ code: 117, indent: 0, parameters: [4] }, { scripts: { 4: 'sunrise' } }), { t: 'call', script: 'sunrise', args: [] });
  assert.deepEqual(one({ code: 303, indent: 0, parameters: [2, 6] }), { t: 'nameEntry', hero: 'p2', prompt: '', maxLength: 6 });
  // an unsupported conditional branch keeps its branches but always runs "then"
  const actorBranch = RM.commands([
    { code: 111, indent: 0, parameters: [4, 1, 0, 0] },
    { code: 115, indent: 1, parameters: [] },
    { code: 412, indent: 0, parameters: [] },
  ], {});
  assert.equal(actorBranch.commands[0].t, 'comment');
  assert.equal(actorBranch.commands[1].t, 'if');
  assert.equal(actorBranch.commands[1].when, null);
  assert.ok(actorBranch.problems.some(p => p.code === 'unsupported-condition'));
});

test('rpgmaker: move route codes 1-45 become Kit route steps', () => {
  const route = { list: [
    { code: 1 }, { code: 2 }, { code: 3 }, { code: 4 }, { code: 9 }, { code: 10 }, { code: 11 },
    { code: 14, parameters: [1, -2] }, { code: 15, parameters: [60] },
    { code: 16 }, { code: 17 }, { code: 18 }, { code: 19 }, { code: 24 }, { code: 25 },
    { code: 29, parameters: [5] }, { code: 33 }, { code: 35 }, { code: 37 }, { code: 39 }, { code: 40 },
    { code: 44, parameters: [{ name: 'Jump1' }] }, { code: 0 },
  ] };
  assert.deepEqual(RM.routeSteps(route, {}), [
    'down', 'left', 'right', 'up', 'randomStep', 'towardHero', 'awayHero',
    'jump:1,-2', 'wait:1000', 'face:down', 'face:left', 'face:right', 'face:up',
    'turnRandom', 'faceHero', 'speed:7.5', 'stepAnim:on', 'dirFix:on', 'through:on', 'visible:off', 'visible:on',
    'sound:jump1',
  ]);
  const problems = [];
  const bag = { once: (s, c, k, m) => { problems.push(c); return null; } };
  assert.deepEqual(RM.routeSteps({ list: [{ code: 5 }, { code: 12 }] }, { problems: bag }), ['down', 'left']);
  assert.deepEqual(problems, ['route-diagonal', 'route-step-dropped']);
  assert.equal(RM.speedToTiles(4), 3.75, 'MV speed 4 = 2^4/256 tiles per frame at 60fps');
  assert.equal(RM.frequencyToKit(3), 5);
});

test('rpgmaker: a two-page event becomes a two-page object, in MV order', () => {
  const r = runImport();
  const obj = r.maps['willow-town'].objects.find(o => o.id === 'old-bran');
  assert.equal(obj.type, 'npc');
  assert.equal(obj.x, 2);
  assert.equal(obj.y, 2);
  assert.equal(obj.pages.length, 2);
  // MV picks the HIGHEST matching page, Kit the LAST — so the order must survive untouched
  assert.equal(obj.pages[0].when, null);
  assert.deepEqual(obj.pages[1].when, { kind: 'self', key: 'a', op: '==', value: true });
  assert.equal(obj.pages[0].layer, 'same', 'priorityType 1 = same as characters');
  assert.equal(obj.pages[0].sprite, 'villagers-2');
  assert.equal(obj.pages[0].visible, true);
  assert.equal(obj.pages[0].behaviour.kind, 'wander', 'moveType 1');
  assert.deepEqual(Object.keys(obj.pages[0].on), ['interact'], 'trigger 0 = action button');
  const say = obj.pages[0].on.interact[0];
  assert.equal(say.t, 'say');
  assert.equal(say.text, 'Morning, {p1}. Mind the {color:red}bees{/color}.\nHere, take this.{pause:1000}');
  assert.equal(say.face, 'face-people1-3');
  assert.deepEqual(obj.pages[0].on.interact.map(c => c.t), ['say', 'give', 'sound', 'setSelf']);
  assert.deepEqual(obj.pages[0].on.interact[3], { t: 'setSelf', key: 'a', op: 'set', value: true });
  assert.deepEqual(obj.pages[0].on.interact[1], { t: 'give', item: 'honey-bun', count: 1, notify: false });

  const door = r.maps['willow-town'].objects.find(o => o.id === 'inn-door');
  assert.equal(door.type, 'trigger');
  assert.equal(door.pages[0].layer, 'below', 'priorityType 0 = below characters');
  assert.equal(door.pages[0].visible, false);
  assert.deepEqual(Object.keys(door.pages[0].on), ['step'], 'trigger 1 = player touch');
  assert.deepEqual(door.pages[0].on.step[1], { t: 'transfer', map: 'inn', x: 1, y: 1, dir: 'down', fade: true });
});

test('rpgmaker: common events become scripts with their trigger and switch gate', () => {
  const r = runImport();
  assert.deepEqual(Object.keys(r.scripts).sort(), ['gate-riddle', 'sunrise']);
  const sunrise = r.scripts.sunrise;
  assert.equal(sunrise.trigger, 'auto');
  assert.deepEqual(sunrise.when, { kind: 'var', name: 'sunrise-done', op: '==', value: true });
  assert.deepEqual(sunrise.body.map(c => c.t), ['tint', 'setVar', 'setVar']);
  assert.deepEqual(sunrise.body[2], { t: 'setVar', name: 'sunrise-done', op: 'set', value: false });
  const gate = r.scripts['gate-riddle'];
  assert.equal(gate.trigger, 'call');
  assert.equal(gate.when, null);
  assert.equal(gate.body[0].t, 'if');
  assert.deepEqual(gate.body[0].then.map(c => c.t), ['say', 'moveRoute']);
  assert.deepEqual(gate.body[0].then[1].steps, ['up', 'up', 'wait:500']);
  assert.equal(gate.body[0].else[0].t, 'choice');
  assert.equal(gate.body[0].else[0].options.length, 2);
  assert.equal(gate.body[1].t, 'comment', 'the plugin command survived as a comment');
});

test('rpgmaker: character sheets slice into 8 sprites with the right rects', () => {
  const r = RM.characters('Villagers', { asset: assetResolver(), imageDir: 'img/' });
  assert.equal(r.sprites.length, 8);
  assert.deepEqual(r.sheet, { asset: 'img-characters-villagers', big: false, noOffset: false, cols: 12, rows: 8, frameW: 8, frameH: 12, count: 8 });
  const first = r.sprites[0];
  assert.equal(first.id, 'villagers-0');
  assert.equal(first.image, 'img-characters-villagers', 'the asset id comes from opts.asset');
  assert.deepEqual(Object.keys(first.frames), ['down', 'left', 'right', 'up']);
  // MV rests on the middle column, Kit's frame 0 is the standing one: columns 1, 0, 2
  assert.deepEqual(first.frames.down, [
    { x: 8, y: 0, w: 8, h: 12 }, { x: 0, y: 0, w: 8, h: 12 }, { x: 16, y: 0, w: 8, h: 12 },
  ]);
  assert.deepEqual(first.frames.up[0], { x: 8, y: 36, w: 8, h: 12 }, 'row 3 = up ((8 - 2) / 2)');
  assert.deepEqual(first.frames.right[0], { x: 8, y: 24, w: 8, h: 12 }, 'MV has a real right row — keep it');
  // character 5 sits in block (1, 1) of the 4x2 grid: blockX = 1 * 3, blockY = 1 * 4
  assert.deepEqual(r.sprites[5].frames.down[0], { x: (3 + 1) * 8, y: 4 * 12, w: 8, h: 12 });
  assert.equal(r.sprites[7].id, 'villagers-7');
  // KIT.entities.frame honours a real `right` row instead of mirroring `left`
  const e = KIT.entities.create({ id: 'x', sprite: 'villagers-0', dir: 'right' });
  KIT.registry('sprites').add(Object.assign({ replace: true }, first));
  assert.equal(KIT.entities.frame(e).mirror, false);
  assert.equal(KIT.entities.frame(e).dir, 'right');

  // a '$' sheet is one big character filling the whole image
  const big = RM.characters('$Boss', { asset: () => ({ id: 'boss', src: 'x.png', w: 72, h: 96 }) });
  assert.equal(big.sprites.length, 1);
  assert.equal(big.sprites[0].id, 'boss');
  assert.deepEqual(big.sheet.frameW, 24);
  assert.deepEqual(big.sheet.frameH, 24);
  assert.deepEqual(RM.signOf('!$Door'), { sign: '!$', name: 'Door', big: true, noOffset: true });
});

test('rpgmaker: faces slice 4x2 and are attached to Show Text', () => {
  const r = RM.faces('People1', { asset: assetResolver(), imageDir: 'img/' });
  assert.equal(r.faces.length, 8);
  assert.deepEqual(r.sheet, { asset: 'img-faces-people1', cols: 4, rows: 2, frameW: 16, frameH: 16 });
  assert.deepEqual(r.faces[3].art, { image: 'img-faces-people1', frame: { x: 48, y: 0, w: 16, h: 16 } });
  assert.deepEqual(r.faces[4].art.frame, { x: 0, y: 16, w: 16, h: 16 });
});

test('rpgmaker: assets, items and stats', () => {
  const r = runImport();
  assert.deepEqual(Object.keys(r.assets).sort(), ['img-characters-villagers', 'img-faces-people1', 'img-tilesets-willow-a2', 'img-tilesets-willow-b']);
  assert.deepEqual(r.assets['img-tilesets-willow-b'], { kind: 'image', src: 'fixtures/img/tilesets/Willow_B.png', w: 128, h: 128, from: 'rpgmaker-mv:img/tilesets/Willow_B.png' });
  assert.deepEqual(Object.keys(r.items), ['honey-bun']);
  assert.equal(r.items['honey-bun'].name, 'Honey Bun');
  assert.deepEqual(r.project.start, { map: 'willow-town', x: 1, y: 1, dir: 'down' });
  assert.equal(r.project.meta.title, 'Willow Town');
  assert.equal(r.stats.maps, 2);
  assert.equal(r.stats.events, 2);
  assert.equal(r.stats.pages, 3);
  assert.equal(r.stats.sprites, 8);
  assert.equal(r.stats.faces, 8);
  assert.equal(r.stats.scripts, 2);
  assert.equal(r.stats.commands.unsupported, 1, 'only the plugin command');
  assert.ok(r.stats.commands.translated > r.stats.commands.unsupported);
  assert.equal(r.stats.problems.error, 0, 'nothing fatal');
  // an unresolved asset is a problem, never a thrown error
  const noResolver = RM.project(loadFiles(), {});
  assert.ok(noResolver.problems.some(p => p.code === 'asset-unresolved'));
  assert.equal(errorsOf(noResolver.problems).length, 0);
});

test('rpgmaker: re-importing the same files produces exactly the same result', () => {
  const a = runImport(), b = runImport();
  assert.equal(KIT.stableStringify(a.maps), KIT.stableStringify(b.maps));
  assert.equal(KIT.stableStringify(a.tiles), KIT.stableStringify(b.tiles));
  assert.equal(KIT.stableStringify(a.vars), KIT.stableStringify(b.vars));
  assert.equal(KIT.stableStringify(a.scripts), KIT.stableStringify(b.scripts));
});

test('rpgmaker: a prefix moves every id out of the way', () => {
  const r = runImport({ prefix: 'willow' });
  assert.deepEqual(Object.keys(r.maps).sort(), ['willow:inn', 'willow:willow-town']);
  assert.ok(r.tiles.every(t => t.id.startsWith('willow:')));
  assert.equal(r.maps['willow:willow-town'].objects[0].pages[0].sprite, 'willow:villagers-2');
  assert.equal(r.project.start.map, 'willow:willow-town');
});

// ---------------------------------------------------------------------------
// The imported project, run for real
// ---------------------------------------------------------------------------

/** Fold a Result into a blank project and register its art, the way merge does. */
function toProject(r) {
  const tiles = KIT.registry('tiles');
  for (const t of r.tiles) tiles.add(Object.assign({}, t, { replace: true }));
  const sprites = KIT.registry('sprites');
  for (const s of r.sprites) sprites.add(Object.assign({}, s, { replace: true }));
  const faces = KIT.registry('faces');
  for (const f of r.faces) faces.add(Object.assign({}, f, { replace: true }));
  const raw = Object.assign({ version: 3 }, r.project, {
    meta: Object.assign({ id: 'willow', pitch: 'Robin wants a honey bun. Old Bran has one.' }, r.project.meta),
    assets: r.assets, maps: r.maps, scripts: r.scripts, vars: r.vars, items: r.items,
    heroes: [{ id: 'p1', name: 'Robin', sprite: 'villagers-0' }],
  });
  return P.normalize(raw);
}

test('rpgmaker: the imported project passes normalize with no error problems', () => {
  const { project, problems } = toProject(runImport());
  assert.deepEqual(errorsOf(problems), [], JSON.stringify(errorsOf(problems), null, 2));
  assert.equal(project.maps['willow-town'].layers.ground.length, 30);
  assert.equal(project.maps['willow-town'].layers.regions[4 * 6 + 2], 3);
  assert.ok(project.vars['sunrise-done']);
});

test('rpgmaker: the imported self-switch page takes over once the first page has run', async () => {
  const { project, problems } = toProject(runImport());
  assert.deepEqual(errorsOf(problems), []);
  const fake = KIT.interpreter.fakeCtx({ project });
  const save = { vars: {}, inventory: {}, objects: {}, heroes: [{}], overlays: {}, meta: {} };
  for (const [k, v] of Object.entries(project.vars)) save.vars[k] = v.default;
  const ports = { io: fake.io, audio: fake.audio, screen: fake.screen, pictures: fake.pictures, game: fake.game, map: fake.map };
  const world = KIT.world.create({ project, save, ports, rng: KIT.rng(7) });
  const said = () => fake.log.filter(e => e.port === 'io' && e.name === 'say').map(e => e.args[0].text);

  await world.enterMap('willow-town', 2, 3, 'up');
  const bran = world.entities.find(e => e.id === 'old-bran');
  assert.equal(bran.pageIndex, 0, 'page 1 while self switch A is off');

  assert.ok(await world.interact(0));
  assert.equal(said().slice(-1)[0], 'Morning, Robin. Mind the {color:red}bees{/color}.\nHere, take this.{pause:1000}',
    '{p1} resolved to the hero name and the MV codes became Kit codes');
  assert.equal(save.inventory['honey-bun'], 1, 'Change Items gave the item');
  assert.equal(save.objects['willow-town:old-bran'].self.a, true, 'Control Self Switch A set self.a');
  assert.equal(world.entities.find(e => e.id === 'old-bran').pageIndex, 1, 'the self-switch page is now active');

  await world.interact(0);
  assert.equal(said().slice(-1)[0], 'Buns keep you honest. 0 coins left, eh?', '{var:coins} read the imported variable');
});

test('rpgmaker: the imported door transfers the hero to the other map', async () => {
  const { project } = toProject(runImport());
  const fake = KIT.interpreter.fakeCtx({ project });
  const save = { vars: {}, inventory: {}, objects: {}, heroes: [{}], overlays: {}, meta: {} };
  for (const [k, v] of Object.entries(project.vars)) save.vars[k] = v.default;
  const world = KIT.world.create({ project, save, rng: KIT.rng(3),
    ports: { io: fake.io, audio: fake.audio, screen: fake.screen, pictures: fake.pictures, game: fake.game,
      map: Object.assign({}, fake.map, { transfer: (o) => world.enterMap(o.map, o.x, o.y, o.dir) }) } });
  await world.enterMap('willow-town', 4, 4, 'down');
  await world.move(0, 'right');
  assert.equal(world.map.id, 'inn');
  assert.equal(world.hero().x, 1);
  assert.equal(world.hero().y, 1);
});

test('rpgmaker: odd input is data, not a crash', () => {
  assert.deepEqual(RM.commands([], {}).commands, []);
  assert.deepEqual(RM.commands(null, {}).commands, []);
  assert.deepEqual(RM.commands([{ code: 0, indent: 0, parameters: [] }], {}).commands, []);
  assert.deepEqual(RM.detect(null).ok, false);
  assert.deepEqual(RM.routeSteps(null, {}), []);
  assert.equal(RM.convertText(null, {}), '');
  // a block that closes without opening ends the list; anything after it is reported, not thrown
  const stray = RM.commands([
    { code: 412, indent: 0, parameters: [] },
    { code: 250, indent: 0, parameters: [{ name: 'Bell' }] },
  ], {});
  assert.deepEqual(stray.commands, []);
  assert.ok(stray.problems.some(p => p.code === 'stray-command'));
  // a map that points at a tileset nobody shipped still imports
  const files = loadFiles();
  files['Tilesets.json'] = [null];
  const r = RM.project(files, { asset: assetResolver() });
  assert.ok(r.problems.some(p => p.code === 'unknown-tileset'));
  assert.equal(errorsOf(r.problems).length, 0);
  assert.equal(r.maps['willow-town'].layers.ground.filter(Boolean).length, 30, 'the tiles are still placed, just without art');
  assert.equal(r.tiles[0].art, null);
});

test('rpgmaker: audio is named but never invented', () => {
  const r = runImport();
  const audio = r.problems.filter(p => p.code === 'audio-not-imported').map(p => p.message);
  assert.equal(audio.length, 3, "Item1, Door1 and the inn's BGM");
  assert.ok(audio.some(m => /'item1'/.test(m)));
  const door = r.maps['willow-town'].objects.find(o => o.id === 'inn-door');
  assert.deepEqual(door.pages[0].on.step[0], { t: 'sound', id: 'door1', volume: 0.9 });
});
