// imported images — Kit content file, generated by KIT.project.exportFiles (hand edits are fine; keep it valid JSON inside).
// kind: assets  id: demo
// project.js registers KIT.content.projects["demo"]; each maps/<id>.js registers KIT.content.maps["demo"][<id>].
// KIT.project.fromContent("demo") assembles the project again; KIT.project.importFiles({ path: text }) parses the texts.
//
// The demo's art is all drawn here (js/art/*.js), so this table starts empty.
// `node tools/import.js <file> --into js/content/demo` fills it in: every image
// it copies into js/content/demo/assets/ is listed here by id. index.html
// already loads this file, so an import needs no hand-editing of the page.
(function (root, data) {
  var KIT = root.KIT = root.KIT || {};
  var content = KIT.content = KIT.content || {};
  (content.assets = content.assets || {})["demo"] = data;
})(typeof window !== 'undefined' ? window : globalThis,
{
}
);
