// Our Adventure — Kit content file, generated by KIT.project.exportFiles (hand edits are fine; keep it valid JSON inside).
// kind: project  id: demo
// project.js registers KIT.content.projects["demo"]; each maps/<id>.js registers KIT.content.maps["demo"][<id>].
// KIT.project.fromContent("demo") assembles the project again; KIT.project.importFiles({ path: text }) parses the texts.
(function (root, data) {
  var KIT = root.KIT = root.KIT || {};
  var content = KIT.content = KIT.content || {};
  (content.projects = content.projects || {})["demo"] = data;
})(typeof window !== 'undefined' ? window : globalThis,
{
  "assets": {},
  "autotiles": {
    "default": {
      "groups": [],
      "source": "terrain"
    }
  },
  "fragments": [
    {
      "body": "Petting, berries, little jobs, decorating. What do they do while we are away?",
      "folder": "Ideas",
      "id": "idea-garden",
      "kind": "note",
      "tags": ["garden"],
      "title": "Garden ideas"
    },
    {
      "body": "\"The rain sounds different under the trees.\"",
      "folder": "Lines",
      "id": "line-rain",
      "kind": "dialogue",
      "tags": ["weather"],
      "title": "Rain line"
    },
    {
      "body": "A room you arrange yourself. Errands they run while you are out. Someone leaving a berry by the door because they thought of you.",
      "folder": "Ideas",
      "id": "idea-home",
      "kind": "note",
      "tags": ["home", "jobs"],
      "title": "After catching"
    },
    {
      "body": "Nobody faints. You throw a ball, they wobble, and either they come with you or they do not — and if they do not, you can always say hello again tomorrow.",
      "folder": "Ideas",
      "id": "idea-mons",
      "kind": "note",
      "tags": ["mons", "catching"],
      "title": "Befriending, not fighting"
    }
  ],
  "heroes": [
    {
      "id": "p1",
      "name": "Player 1",
      "recolor": {},
      "sprite": "hero-boy"
    },
    {
      "id": "p2",
      "name": "Player 2",
      "recolor": {},
      "sprite": "hero-girl"
    }
  ],
  "items": {
    "berry": {
      "desc": "Sweet. Calms a nervous Pokémon — and cheers up the one walking with you.",
      "icon": "berry",
      "kind": "berry",
      "name": "Berry",
      "note": "",
      "props": {
        "calm": 1,
        "friendship": 10,
        "golden": false
      }
    },
    "cushion": {
      "desc": "For sitting on the floor.",
      "icon": null,
      "kind": "furniture",
      "name": "Cushion",
      "note": "",
      "props": {
        "layer": "deco",
        "solid": false,
        "variants": [
          {
            "dir": "down",
            "label": "Plump",
            "tile": "cushion",
            "tile2": null
          }
        ]
      }
    },
    "golden-berry": {
      "desc": "Rare and very sweet. The next ball you throw will surely work.",
      "icon": "golden-berry",
      "kind": "berry",
      "name": "Golden Berry",
      "note": "",
      "props": {
        "calm": 1,
        "friendship": 20,
        "golden": true
      }
    },
    "pokeball": {
      "desc": "For making friends.",
      "icon": "pokeball",
      "kind": "ball",
      "name": "Poké Ball",
      "note": "",
      "props": {
        "power": 1
      }
    },
    "pot-plant": {
      "desc": "It likes the window.",
      "icon": null,
      "kind": "furniture",
      "name": "Pot Plant",
      "note": "",
      "props": {
        "layer": "deco",
        "solid": true,
        "variants": [
          {
            "dir": "down",
            "label": "In its pot",
            "tile": "plant",
            "tile2": null
          }
        ]
      }
    },
    "rug": {
      "desc": "Warm underfoot.",
      "icon": null,
      "kind": "furniture",
      "name": "Rug",
      "note": "",
      "props": {
        "layer": "ground",
        "solid": false,
        "variants": [
          {
            "dir": "down",
            "label": "Woven",
            "tile": "rug",
            "tile2": null
          },
          {
            "dir": "down",
            "label": "Red",
            "tile": "carpet-red",
            "tile2": null
          },
          {
            "dir": "down",
            "label": "Blue",
            "tile": "carpet-blue",
            "tile2": null
          }
        ]
      }
    },
    "table-set": {
      "desc": "Somewhere to put a cup.",
      "icon": null,
      "kind": "furniture",
      "name": "Table And Chair",
      "note": "",
      "props": {
        "layer": "deco",
        "solid": true,
        "variants": [
          {
            "dir": "right",
            "label": "Chair on the right",
            "tile": "table",
            "tile2": "chair"
          },
          {
            "dir": "down",
            "label": "Chair below",
            "tile": "table",
            "tile2": "chair"
          }
        ]
      }
    }
  },
  "meta": {
    "author": "",
    "id": "demo",
    "pitch": "Two friends share one phone to wander a small town and befriend the Pokémon they meet. Everything you make friends with keeps living in the garden while you are away.",
    "subtitle": "for you ♥",
    "title": "Our Adventure"
  },
  "modules": ["mons", "home"],
  "packs": {
    "home": {
      "giftItems": ["berry", "golden-berry"],
      "giftSpot": {
        "map": "home",
        "x": 4,
        "y": 8
      },
      "tuning": {
        "feedFriendship": 10,
        "giftChance": 0.2,
        "giftFriendship": 1,
        "jobFriendship": 8,
        "maxGifts": 2,
        "moodDriftMinutes": 90,
        "petFriendship": 6,
        "suitedSpeed": 0.75
      },
      "workers": "auto"
    },
    "mons": {
      "awayBonus": 4,
      "awayHours": 20,
      "ball": "pokeball",
      "berries": ["berry", "golden-berry"],
      "berry": "berry",
      "berryBonus": 10,
      "defaultProfile": "friendly",
      "difficulty": "gentle",
      "encounters": {},
      "favouriteBerryBonus": 5,
      "followStepBonus": 1,
      "followers": true,
      "garden": null,
      "goldenBerry": "golden-berry",
      "petBonus": 3,
      "profiles": [
        {
          "actions": [
            {
              "effects": {},
              "id": "throw",
              "item": "pokeball",
              "kind": "throw",
              "label": "mons-act-throw",
              "power": 1
            },
            {
              "effects": {
                "band": 0.05,
                "calm": 1,
                "chance": 0.12
              },
              "id": "berry",
              "item": "berry",
              "kind": "offer",
              "label": "mons-act-berry"
            },
            {
              "effects": {
                "calm": 1,
                "guarantee": true
              },
              "id": "golden",
              "item": "golden-berry",
              "kind": "offer",
              "label": "mons-act-golden"
            },
            {
              "effects": {
                "curious": 0.34
              },
              "id": "talk",
              "kind": "talk",
              "label": "mons-act-talk"
            },
            {
              "effects": {},
              "id": "leave",
              "kind": "leave",
              "label": "mons-act-leave"
            }
          ],
          "art": {
            "ring": {
              "calmWidth": 0.06,
              "center": 0.34,
              "speed": 0.55,
              "width": 0.18
            },
            "scale": 4,
            "throwMs": 520,
            "wobbleMs": 460
          },
          "id": "friendly",
          "label": "Making friends",
          "rules": {
            "calmBonus": 0.12,
            "curiousBonus": 0.08,
            "fleeAfter": 3,
            "fleeChance": 0.35,
            "maxCalm": 3
          },
          "strings": {
            "appeared": "mons-appeared",
            "appearedNew": "mons-appeared-new",
            "broke": "mons-broke",
            "calmed": "mons-calmed",
            "curious": "mons-curious",
            "fled": "mons-fled",
            "golden": "mons-golden",
            "gotcha": "mons-gotcha",
            "great": "mons-great",
            "miss": "mons-miss",
            "nickname": "mons-nickname",
            "noBalls": "mons-no-balls",
            "noItem": "mons-no-item",
            "ok": "mons-ok",
            "perfect": "mons-perfect",
            "ranAway": "mons-ran",
            "talk": "mons-talk",
            "wobble": "mons-wobble"
          }
        }
      ],
      "rarity": {},
      "shinyChance": 0.02,
      "starters": {
        "ask": true,
        "friendship": 70,
        "var": "starter"
      },
      "stepsPerFriendship": 128
    }
  },
  "scripts": {
    "clear-stands": {
      "body": [
        {
          "persistent": true,
          "t": "erase",
          "target": "obj:stand-pikachu"
        },
        {
          "persistent": true,
          "t": "erase",
          "target": "obj:stand-butterfree"
        },
        {
          "persistent": true,
          "t": "erase",
          "target": "obj:stand-clefable"
        }
      ],
      "label": "Clear the other stands",
      "note": "The two you did not choose go back to sleep.",
      "params": [],
      "trigger": "call",
      "when": null
    },
    "give-balls": {
      "body": [
        {
          "count": 3,
          "item": "pokeball",
          "notify": true,
          "t": "give"
        },
        {
          "id": "item",
          "t": "sound",
          "volume": 1
        }
      ],
      "label": "Give Poké Balls",
      "note": "Called by the hiker; n is there for the editor to show parameters.",
      "params": ["n"],
      "trigger": "call",
      "when": null
    },
    "intro": {
      "body": [
        {
          "color": "#000000",
          "ms": 0,
          "t": "fadeOut"
        },
        {
          "ms": 600,
          "t": "fadeIn"
        },
        {
          "ms": 2000,
          "subtitle": "for you ♥",
          "t": "chapter",
          "title": "Our Adventure"
        },
        {
          "bg": "window",
          "face": null,
          "position": "bottom",
          "t": "say",
          "text": "{p1} and {p2} wake up to a bright new morning.",
          "who": ""
        },
        {
          "max": 6,
          "min": 1,
          "name": "introDone",
          "op": "set",
          "t": "setVar",
          "value": true,
          "var": null
        }
      ],
      "label": "Intro",
      "note": "Runs once, from the trigger by the bedroom door.",
      "params": [],
      "trigger": "call",
      "when": null
    }
  },
  "settings": {
    "clock": {
      "awayCapMinutes": 4320,
      "awayMinutesPerRealMinute": 1,
      "enabled": true,
      "minutesPerSecond": 6,
      "minutesPerStep": 1,
      "stampEverySeconds": 20
    },
    "coop": {
      "enabled": false
    },
    "palette": {
      "amount": 0,
      "remap": {},
      "tint": null
    },
    "textSpeed": "normal",
    "tileSize": 16,
    "viewport": {
      "h": 12,
      "w": 16
    },
    "zoom": "auto"
  },
  "start": {
    "dir": "down",
    "map": "home",
    "x": 5,
    "y": 6
  },
  "strings": {},
  "terrains": [
    {
      "base": "grass",
      "color": "#78c850",
      "id": 1,
      "name": "Grass"
    },
    {
      "base": "path",
      "color": "#d8b878",
      "id": 2,
      "name": "Path"
    }
  ],
  "testStates": [
    {
      "dir": "down",
      "id": "after-starter",
      "inventory": {
        "berry": 3,
        "pokeball": 5
      },
      "label": "After choosing a partner",
      "map": "town",
      "modules": {},
      "vars": {
        "chapter": 1,
        "hasStarter": true,
        "introDone": true,
        "starter": "pikachu"
      },
      "x": 12,
      "y": 8
    },
    {
      "dir": "down",
      "id": "home-life",
      "inventory": {
        "berry": 3,
        "cushion": 2,
        "pot-plant": 2,
        "rug": 1,
        "table-set": 1
      },
      "label": "Home: furniture in the bag, a friend to send",
      "map": "home",
      "modules": {},
      "vars": {
        "chapter": 1,
        "friendship": 3,
        "hasStarter": true,
        "introDone": true,
        "starter": "pikachu"
      },
      "x": 5,
      "y": 6
    },
    {
      "dir": "down",
      "id": "mons-grass",
      "inventory": {
        "berry": 5,
        "golden-berry": 1,
        "pokeball": 9
      },
      "label": "Pokémon: in the tall grass with a full bag",
      "map": "route",
      "modules": {},
      "vars": {
        "chapter": 1,
        "hasStarter": true,
        "introDone": true,
        "starter": "pikachu"
      },
      "x": 4,
      "y": 6
    }
  ],
  "vars": {
    "boxEmptied": {
      "default": false,
      "group": "Home",
      "label": "Moving box emptied",
      "type": "bool"
    },
    "catFound": {
      "default": false,
      "group": "Home",
      "label": "The cat came home",
      "type": "bool"
    },
    "chapter": {
      "default": 0,
      "group": "Story",
      "label": "Chapter",
      "type": "number"
    },
    "friendship": {
      "default": 0,
      "group": "Story",
      "label": "Kindness",
      "type": "number"
    },
    "gateOpen": {
      "default": false,
      "group": "Route",
      "label": "Old gate opened",
      "type": "bool"
    },
    "hasStarter": {
      "default": false,
      "group": "Story",
      "label": "Has a partner",
      "type": "bool"
    },
    "introDone": {
      "default": false,
      "group": "Story",
      "label": "Intro played",
      "type": "bool"
    },
    "postRun": {
      "default": false,
      "group": "Home",
      "label": "The post was run",
      "type": "bool"
    },
    "starter": {
      "default": "",
      "group": "Story",
      "label": "Chosen partner",
      "type": "string"
    }
  },
  "version": 3,
  "world": {
    "connections": [
      {
        "a": "town",
        "b": "route",
        "offset": -3,
        "side": "s"
      }
    ],
    "maps": {
      "garden": {
        "folder": "Chapter 1",
        "x": 0,
        "y": 1
      },
      "home": {
        "folder": "Chapter 1",
        "x": 0,
        "y": 0
      },
      "lab": {
        "folder": "Chapter 1",
        "x": 2,
        "y": 0
      },
      "route": {
        "folder": "Chapter 1",
        "x": 1,
        "y": 1
      },
      "town": {
        "folder": "Chapter 1",
        "x": 1,
        "y": 0
      }
    }
  }
}
);
