// Our Adventure — Kit content file, generated by KIT.project.exportFiles (hand edits are fine; keep it valid JSON inside).
// kind: project  id: demo
// project.js registers KIT.content.projects["demo"]; each maps/<id>.js registers KIT.content.maps["demo"][<id>].
// KIT.project.fromContent("demo") assembles the project again; KIT.project.importFiles({ path: text }) parses the texts.
(function (root, data) {
  var KIT = root.KIT = root.KIT || {};
  var content = KIT.content = KIT.content || {};
  (content.projects = content.projects || {})["demo"] = data;
})(typeof window !== 'undefined' ? window : globalThis,
{
  "autotiles": {
    "default": {
      "groups": [],
      "source": "terrain"
    }
  },
  "fragments": [
    {
      "body": "Petting, berries, little jobs, decorating. What do they do while we are away?",
      "folder": "Ideas",
      "id": "idea-garden",
      "kind": "note",
      "tags": ["garden"],
      "title": "Garden ideas"
    },
    {
      "body": "\"The rain sounds different under the trees.\"",
      "folder": "Lines",
      "id": "line-rain",
      "kind": "dialogue",
      "tags": ["weather"],
      "title": "Rain line"
    }
  ],
  "heroes": [
    {
      "id": "p1",
      "name": "Player 1",
      "recolor": {},
      "sprite": "hero-boy"
    },
    {
      "id": "p2",
      "name": "Player 2",
      "recolor": {},
      "sprite": "hero-girl"
    }
  ],
  "items": {
    "berry": {
      "desc": "Sweet. Calms a nervous Pokémon.",
      "icon": "berry",
      "kind": "berry",
      "name": "Berry",
      "note": "",
      "props": {}
    },
    "golden-berry": {
      "desc": "Rare and very sweet.",
      "icon": "golden-berry",
      "kind": "berry",
      "name": "Golden Berry",
      "note": "",
      "props": {}
    },
    "pokeball": {
      "desc": "For making friends.",
      "icon": "pokeball",
      "kind": "ball",
      "name": "Poké Ball",
      "note": "",
      "props": {}
    }
  },
  "meta": {
    "author": "",
    "id": "demo",
    "pitch": "Two friends share one phone to wander a small town and befriend the Pokémon they meet. Everything you make friends with keeps living in the garden while you are away.",
    "subtitle": "for you ♥",
    "title": "Our Adventure"
  },
  "modules": [],
  "packs": {},
  "scripts": {
    "clear-stands": {
      "body": [
        {
          "persistent": true,
          "t": "erase",
          "target": "obj:stand-pikachu"
        },
        {
          "persistent": true,
          "t": "erase",
          "target": "obj:stand-butterfree"
        },
        {
          "persistent": true,
          "t": "erase",
          "target": "obj:stand-clefable"
        }
      ],
      "label": "Clear the other stands",
      "note": "The two you did not choose go back to sleep.",
      "params": [],
      "trigger": "call",
      "when": null
    },
    "give-balls": {
      "body": [
        {
          "count": 3,
          "item": "pokeball",
          "notify": true,
          "t": "give"
        },
        {
          "id": "item",
          "t": "sound",
          "volume": 1
        }
      ],
      "label": "Give Poké Balls",
      "note": "Called by the hiker; n is there for the editor to show parameters.",
      "params": ["n"],
      "trigger": "call",
      "when": null
    },
    "intro": {
      "body": [
        {
          "color": "#000000",
          "ms": 0,
          "t": "fadeOut"
        },
        {
          "ms": 600,
          "t": "fadeIn"
        },
        {
          "ms": 2000,
          "subtitle": "for you ♥",
          "t": "chapter",
          "title": "Our Adventure"
        },
        {
          "bg": "window",
          "face": null,
          "position": "bottom",
          "t": "say",
          "text": "{p1} and {p2} wake up to a bright new morning.",
          "who": ""
        },
        {
          "max": 6,
          "min": 1,
          "name": "introDone",
          "op": "set",
          "t": "setVar",
          "value": true,
          "var": null
        }
      ],
      "label": "Intro",
      "note": "Runs once, from the trigger by the bedroom door.",
      "params": [],
      "trigger": "call",
      "when": null
    }
  },
  "settings": {
    "clock": {
      "enabled": false,
      "minutesPerSecond": 0,
      "minutesPerStep": 1
    },
    "coop": {
      "enabled": false
    },
    "encounterRate": 12,
    "palette": {
      "amount": 0,
      "remap": {},
      "tint": null
    },
    "textSpeed": "normal",
    "tileSize": 16,
    "viewport": {
      "h": 12,
      "w": 16
    },
    "zoom": "auto"
  },
  "start": {
    "dir": "down",
    "map": "home",
    "x": 5,
    "y": 6
  },
  "strings": {
    "bag": "Bag",
    "cancel": "Cancel",
    "continue": "Continue",
    "empty-bag": "Your bag is empty.",
    "got-item": "Got {count} {item}!",
    "lost-item": "Lost {count} {item}.",
    "name-prompt": "What is your name?",
    "new-game": "New Game",
    "no": "No",
    "number-prompt": "Enter a number",
    "ok": "OK",
    "quit": "Quit to title",
    "save": "Save",
    "save-failed": "Could not save.",
    "save-prompt": "Save your progress?",
    "saved": "Saved.",
    "settings": "Settings",
    "the-end": "The End",
    "timer-up": "Time is up!",
    "yes": "Yes"
  },
  "terrains": [
    {
      "base": "grass",
      "color": "#78c850",
      "id": 1,
      "name": "Grass"
    },
    {
      "base": "path",
      "color": "#d8b878",
      "id": 2,
      "name": "Path"
    }
  ],
  "testStates": [
    {
      "dir": "down",
      "id": "after-starter",
      "inventory": {
        "berry": 3,
        "pokeball": 5
      },
      "label": "After choosing a partner",
      "map": "town",
      "modules": {},
      "vars": {
        "chapter": 1,
        "hasStarter": true,
        "introDone": true,
        "starter": "pikachu"
      },
      "x": 12,
      "y": 8
    }
  ],
  "vars": {
    "chapter": {
      "default": 0,
      "group": "Story",
      "label": "Chapter",
      "type": "number"
    },
    "friendship": {
      "default": 0,
      "group": "Story",
      "label": "Kindness",
      "type": "number"
    },
    "gateOpen": {
      "default": false,
      "group": "Route",
      "label": "Old gate opened",
      "type": "bool"
    },
    "hasStarter": {
      "default": false,
      "group": "Story",
      "label": "Has a partner",
      "type": "bool"
    },
    "introDone": {
      "default": false,
      "group": "Story",
      "label": "Intro played",
      "type": "bool"
    },
    "starter": {
      "default": "",
      "group": "Story",
      "label": "Chosen partner",
      "type": "string"
    }
  },
  "version": 3,
  "world": {
    "connections": [
      {
        "a": "town",
        "b": "route",
        "offset": -3,
        "side": "s"
      }
    ],
    "maps": {
      "home": {
        "folder": "Chapter 1",
        "x": 0,
        "y": 0
      },
      "lab": {
        "folder": "Chapter 1",
        "x": 2,
        "y": 0
      },
      "route": {
        "folder": "Chapter 1",
        "x": 1,
        "y": 1
      },
      "town": {
        "folder": "Chapter 1",
        "x": 1,
        "y": 0
      }
    }
  }
}
);
