// The Garden (map) — Kit content file, generated by KIT.project.exportFiles (hand edits are fine; keep it valid JSON inside).
// kind: map  project: demo  id: garden
// project.js registers KIT.content.projects["demo"]; each maps/<id>.js registers KIT.content.maps["demo"][<id>].
// KIT.project.fromContent("demo") assembles the project again; KIT.project.importFiles({ path: text }) parses the texts.
(function (root, data) {
  var KIT = root.KIT = root.KIT || {};
  var content = KIT.content = KIT.content || {};
  var maps = content.maps = content.maps || {};
  (maps["demo"] = maps["demo"] || {})["garden"] = data;
})(typeof window !== 'undefined' ? window : globalThis,
{
  "collision": [
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null
  ],
  "dimensions": {},
  "height": 10,
  "id": "garden",
  "kind": "garden",
  "layers": {
    "above": [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "deco": [
      "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h",
      "fence-v", null, null, null, null, null, null, null, null, null, "tree-tl", "tree-tr", null, "fence-v",
      "fence-v", null, null, null, null, null, null, null, null, null, "tree-bl", "tree-br", null, "fence-v",
      "fence-v", null, null, null, null, null, null, null, null, null, null, null, null, "fence-v",
      "fence-v", null, null, null, null, null, null, null, null, null, null, null, null, "fence-v",
      "fence-v", null, null, null, "bench", null, null, null, null, null, null, null, null, "fence-v",
      "fence-v", null, null, null, null, null, null, null, null, null, null, "flowers-yellow", null, "fence-v",
      "fence-v", null, "flowers-red", null, null, null, null, null, null, null, null, null, null, "fence-v",
      "fence-v", null, null, null, null, null, null, null, null, null, null, null, null, "fence-v",
      "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", null, "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h"
    ],
    "ground": [
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass-2", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass-2", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass-2", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "exit-mat", "grass", "grass", "grass", "grass", "grass", "grass"
    ],
    "regions": [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ],
    "terrain": [
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    ]
  },
  "music": "town",
  "name": "The Garden",
  "note": "",
  "objects": [
    {
      "id": "garden-home",
      "name": "Back door",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {},
          "once": false,
          "props": {
            "dir": "down",
            "fade": true,
            "look": null,
            "sound": null,
            "to": {
              "dir": "up",
              "map": "home",
              "x": 11,
              "y": 8
            }
          },
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "warp",
      "x": 7,
      "y": 9
    },
    {
      "id": "garden-gate",
      "name": "The gate",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "The gate at the end of the garden. This is where everyone comes back to.",
                "who": ""
              },
              {
                "job": "",
                "silent": false,
                "t": "collectJob"
              }
            ]
          },
          "once": false,
          "props": {
            "look": "sign"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "sign",
      "x": 6,
      "y": 1
    },
    {
      "id": "garden-sign",
      "name": "Notice",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Whoever is not out working is here, dozing or pacing or waiting for the door.",
                "who": ""
              },
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "The Jobs page in the menu says how everyone is.",
                "who": ""
              }
            ]
          },
          "once": false,
          "props": {
            "look": "mailbox"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "sign",
      "x": 9,
      "y": 5
    }
  ],
  "props": {},
  "width": 14
}
);
