// Home (map) — Kit content file, generated by KIT.project.exportFiles (hand edits are fine; keep it valid JSON inside).
// kind: map  project: demo  id: home
// project.js registers KIT.content.projects["demo"]; each maps/<id>.js registers KIT.content.maps["demo"][<id>].
// KIT.project.fromContent("demo") assembles the project again; KIT.project.importFiles({ path: text }) parses the texts.
(function (root, data) {
  var KIT = root.KIT = root.KIT || {};
  var content = KIT.content = KIT.content || {};
  var maps = content.maps = content.maps || {};
  (maps["demo"] = maps["demo"] || {})["home"] = data;
})(typeof window !== 'undefined' ? window : globalThis,
{
  "collision": [
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null
  ],
  "height": 10,
  "id": "home",
  "kind": "indoor",
  "layers": {
    "above": [
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "deco": [
      "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top",
      "wall-in", "wall-in", "wall-in", "window-inner", "wall-in", "wall-in", "wall-in", "wall-in", "poster", "wall-in", "wall-in", "wall-in",
      null, "bed-top", null, null, null, null, "plant", null, "chair", "table", "tv", null,
      null, "bed-bottom", null, "bookshelf", "pc", null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "ground": [
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "carpet-red", "carpet-red", "carpet-red", "carpet-red", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "carpet-red", "carpet-red", "carpet-red", "carpet-red", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "carpet-red", "carpet-red", "carpet-red", "carpet-red", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "carpet-red", "carpet-red", "carpet-red", "carpet-red", "floor-wood", "floor-wood",
      "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "exit-mat", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "floor-wood", "exit-mat"
    ],
    "regions": [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ],
    "terrain": [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ]
  },
  "music": "house",
  "name": "Home",
  "note": "",
  "objects": [
    {
      "id": "mom",
      "name": "Mom",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 3,
            "kind": "wander",
            "radius": 2,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Good morning, {p1}! {pause} You and {p2} slept late again.",
                "who": "Mom"
              },
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Take these — you will want them out there.",
                "who": "Mom"
              },
              {
                "count": 5,
                "item": "pokeball",
                "notify": true,
                "t": "give"
              },
              {
                "count": 3,
                "item": "berry",
                "notify": true,
                "t": "give"
              },
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "One ball for each friend you make. {pause} The berries are for when they are shy.",
                "who": "Mom"
              },
              {
                "kind": "♥",
                "t": "balloon",
                "target": "self",
                "wait": false
              },
              {
                "max": 6,
                "min": 1,
                "name": "chapter",
                "op": "set",
                "t": "setVar",
                "value": 1,
                "var": null
              }
            ]
          },
          "once": true,
          "props": {},
          "sprite": "woman",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        },
        {
          "behaviour": {
            "frequency": 3,
            "kind": "wander",
            "radius": 2,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "The Professor is waiting in the lab, you two.",
                "who": "Mom"
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "woman",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": {
            "kind": "var",
            "name": "chapter",
            "op": ">=",
            "value": 1,
            "var": null
          }
        }
      ],
      "type": "npc",
      "x": 8,
      "y": 4
    },
    {
      "id": "pc",
      "name": "PC",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "The PC hums. Everyone you befriend rests in the Garden.",
                "who": ""
              }
            ]
          },
          "once": false,
          "props": {
            "look": "sign"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "sign",
      "x": 4,
      "y": 3
    },
    {
      "id": "tv",
      "name": "TV",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "A cooking show. Someone is very excited about berries.",
                "who": ""
              }
            ]
          },
          "once": false,
          "props": {
            "look": "sign"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "sign",
      "x": 10,
      "y": 2
    },
    {
      "id": "door-out",
      "name": "Front door",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {},
          "once": false,
          "props": {
            "dir": "down",
            "fade": true,
            "look": null,
            "sound": null,
            "to": {
              "dir": "down",
              "map": "town",
              "x": 12,
              "y": 3
            }
          },
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "warp",
      "x": 5,
      "y": 9
    },
    {
      "id": "intro-trigger",
      "name": "Intro",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {
            "enter": [
              {
                "args": [],
                "script": "intro",
                "t": "call"
              },
              {
                "max": 6,
                "min": 1,
                "name": "introDone",
                "op": "set",
                "t": "setVar",
                "value": true,
                "var": null
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": {
            "kind": "var",
            "name": "introDone",
            "op": "==",
            "value": false,
            "var": null
          }
        }
      ],
      "type": "trigger",
      "x": 5,
      "y": 8
    },
    {
      "id": "moving-box",
      "name": "Moving box",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "A box of odds and ends, left over from moving in.",
                "who": ""
              },
              {
                "count": 2,
                "item": "pot-plant",
                "notify": true,
                "t": "give"
              },
              {
                "count": 1,
                "item": "rug",
                "notify": true,
                "t": "give"
              },
              {
                "count": 1,
                "item": "table-set",
                "notify": true,
                "t": "give"
              },
              {
                "count": 2,
                "item": "cushion",
                "notify": true,
                "t": "give"
              },
              {
                "max": 6,
                "min": 1,
                "name": "boxEmptied",
                "op": "set",
                "t": "setVar",
                "value": true,
                "var": null
              },
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Somewhere in here is a home.",
                "who": ""
              }
            ]
          },
          "once": true,
          "props": {
            "look": "crate"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        },
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "An empty box. It has done its work.",
                "who": ""
              }
            ]
          },
          "once": false,
          "props": {
            "look": "crate"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": {
            "kind": "var",
            "name": "boxEmptied",
            "op": "==",
            "value": true,
            "var": null
          }
        }
      ],
      "type": "sign",
      "x": 2,
      "y": 6
    },
    {
      "id": "garden-door",
      "name": "Garden door",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {},
          "once": false,
          "props": {
            "dir": "down",
            "fade": true,
            "look": null,
            "sound": null,
            "to": {
              "dir": "up",
              "map": "garden",
              "x": 7,
              "y": 8
            }
          },
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "warp",
      "x": 11,
      "y": 9
    }
  ],
  "props": {},
  "width": 12
}
);
