// Professor’s Lab (map) — Kit content file, generated by KIT.project.exportFiles (hand edits are fine; keep it valid JSON inside).
// kind: map  project: demo  id: lab
// project.js registers KIT.content.projects["demo"]; each maps/<id>.js registers KIT.content.maps["demo"][<id>].
// KIT.project.fromContent("demo") assembles the project again; KIT.project.importFiles({ path: text }) parses the texts.
(function (root, data) {
  var KIT = root.KIT = root.KIT || {};
  var content = KIT.content = KIT.content || {};
  var maps = content.maps = content.maps || {};
  (maps["demo"] = maps["demo"] || {})["lab"] = data;
})(typeof window !== 'undefined' ? window : globalThis,
{
  "collision": [
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null
  ],
  "dimensions": {},
  "height": 10,
  "id": "lab",
  "kind": "indoor",
  "layers": {
    "above": [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "deco": [
      "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top", "wall-in-top",
      "wall-in", "wall-in", "wall-in", "wall-in", "window-inner", "wall-in", "wall-in", "wall-in", "wall-in", "window-inner", "wall-in", "wall-in", "wall-in", "wall-in",
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, "bookshelf", "bookshelf", null, null, null, null, null, null, "counter", "counter", null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "ground": [
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile",
      "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "exit-mat", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile", "floor-tile"
    ],
    "regions": [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ],
    "terrain": [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ]
  },
  "music": "house",
  "name": "Professor’s Lab",
  "note": "",
  "objects": [
    {
      "id": "prof",
      "name": "Professor",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "enter": [
              {
                "repeat": false,
                "skipBlocked": true,
                "steps": ["down", "down"],
                "t": "moveRoute",
                "target": "self",
                "wait": true
              },
              {
                "kind": "!",
                "t": "balloon",
                "target": "self",
                "wait": true
              },
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "{p1}! {p2}! {pause} Right on time.",
                "who": "Professor"
              },
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "One of these three would like to come with you.",
                "who": "Professor"
              }
            ]
          },
          "once": true,
          "props": {},
          "sprite": "professor",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        },
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Head out to the route when you are ready. {pause} Be kind out there.",
                "who": "Professor"
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "professor",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": {
            "kind": "var",
            "name": "hasStarter",
            "op": "==",
            "value": true,
            "var": null
          }
        },
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Go on, pick one. They have been waiting all morning.",
                "who": "Professor"
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "professor",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "npc",
      "x": 7,
      "y": 4
    },
    {
      "id": "stand-pikachu",
      "name": "Pikachu",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "A sleepy Pikachu looks up at you.",
                "who": ""
              },
              {
                "cancel": "none",
                "options": [
                  {
                    "text": "Yes",
                    "then": [
                      {
                        "max": 6,
                        "min": 1,
                        "name": "starter",
                        "op": "set",
                        "t": "setVar",
                        "value": "pikachu",
                        "var": null
                      },
                      {
                        "max": 6,
                        "min": 1,
                        "name": "hasStarter",
                        "op": "set",
                        "t": "setVar",
                        "value": true,
                        "var": null
                      },
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "Pikachu it is! {pause} Take good care of them.",
                        "who": "Professor"
                      },
                      {
                        "id": "sparkle",
                        "t": "sound",
                        "volume": 1
                      },
                      {
                        "args": [],
                        "script": "clear-stands",
                        "t": "call"
                      }
                    ],
                    "when": null
                  },
                  {
                    "text": "Not yet",
                    "then": [
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "You step back.",
                        "who": ""
                      }
                    ],
                    "when": null
                  }
                ],
                "prompt": "Choose Pikachu?",
                "t": "choice"
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "pokeball",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": {
            "kind": "var",
            "name": "starter",
            "op": "==",
            "value": "",
            "var": null
          }
        }
      ],
      "type": "npc",
      "x": 5,
      "y": 6
    },
    {
      "id": "stand-butterfree",
      "name": "Butterfree",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "A sleepy Butterfree looks up at you.",
                "who": ""
              },
              {
                "cancel": "none",
                "options": [
                  {
                    "text": "Yes",
                    "then": [
                      {
                        "max": 6,
                        "min": 1,
                        "name": "starter",
                        "op": "set",
                        "t": "setVar",
                        "value": "butterfree",
                        "var": null
                      },
                      {
                        "max": 6,
                        "min": 1,
                        "name": "hasStarter",
                        "op": "set",
                        "t": "setVar",
                        "value": true,
                        "var": null
                      },
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "Butterfree it is! {pause} Take good care of them.",
                        "who": "Professor"
                      },
                      {
                        "id": "sparkle",
                        "t": "sound",
                        "volume": 1
                      },
                      {
                        "args": [],
                        "script": "clear-stands",
                        "t": "call"
                      }
                    ],
                    "when": null
                  },
                  {
                    "text": "Not yet",
                    "then": [
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "You step back.",
                        "who": ""
                      }
                    ],
                    "when": null
                  }
                ],
                "prompt": "Choose Butterfree?",
                "t": "choice"
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "pokeball",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": {
            "kind": "var",
            "name": "starter",
            "op": "==",
            "value": "",
            "var": null
          }
        }
      ],
      "type": "npc",
      "x": 7,
      "y": 6
    },
    {
      "id": "stand-clefable",
      "name": "Clefable",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "A sleepy Clefable looks up at you.",
                "who": ""
              },
              {
                "cancel": "none",
                "options": [
                  {
                    "text": "Yes",
                    "then": [
                      {
                        "max": 6,
                        "min": 1,
                        "name": "starter",
                        "op": "set",
                        "t": "setVar",
                        "value": "clefable",
                        "var": null
                      },
                      {
                        "max": 6,
                        "min": 1,
                        "name": "hasStarter",
                        "op": "set",
                        "t": "setVar",
                        "value": true,
                        "var": null
                      },
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "Clefable it is! {pause} Take good care of them.",
                        "who": "Professor"
                      },
                      {
                        "id": "sparkle",
                        "t": "sound",
                        "volume": 1
                      },
                      {
                        "args": [],
                        "script": "clear-stands",
                        "t": "call"
                      }
                    ],
                    "when": null
                  },
                  {
                    "text": "Not yet",
                    "then": [
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "You step back.",
                        "who": ""
                      }
                    ],
                    "when": null
                  }
                ],
                "prompt": "Choose Clefable?",
                "t": "choice"
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "pokeball",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": {
            "kind": "var",
            "name": "starter",
            "op": "==",
            "value": "",
            "var": null
          }
        }
      ],
      "type": "npc",
      "x": 9,
      "y": 6
    },
    {
      "id": "lab-out",
      "name": "Door",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {},
          "once": false,
          "props": {
            "dir": "down",
            "fade": true,
            "look": null,
            "sound": null,
            "to": {
              "dir": "down",
              "map": "town",
              "x": 18,
              "y": 7
            }
          },
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "warp",
      "x": 7,
      "y": 9
    }
  ],
  "props": {},
  "width": 14
}
);
