// Route 1 (map) — Kit content file, generated by KIT.project.exportFiles (hand edits are fine; keep it valid JSON inside).
// kind: map  project: demo  id: route
// project.js registers KIT.content.projects["demo"]; each maps/<id>.js registers KIT.content.maps["demo"][<id>].
// KIT.project.fromContent("demo") assembles the project again; KIT.project.importFiles({ path: text }) parses the texts.
(function (root, data) {
  var KIT = root.KIT = root.KIT || {};
  var content = KIT.content = KIT.content || {};
  var maps = content.maps = content.maps || {};
  (maps["demo"] = maps["demo"] || {})["route"] = data;
})(typeof window !== 'undefined' ? window : globalThis,
{
  "collision": [
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
  ],
  "height": 24,
  "id": "route",
  "kind": "outdoor",
  "layers": {
    "above": [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "deco": [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, "water", "water", "water", null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, "water", "water-lily", "water", null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, "water", "water", "water", null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "tree-tl", "tree-tr", null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "tree-bl", "tree-br", null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, "stump", null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, "tree-tl", "tree-tr", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, "tree-bl", "tree-br", null, null, null, null, null, null, "rock", null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, "log", null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "ground": [
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "ledge-down", "ledge-down", "ledge-down", "ledge-down", "ledge-down", "ledge-down", "ledge-down", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "tall-grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass"
    ],
    "regions": [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ],
    "terrain": [
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    ]
  },
  "music": "route",
  "name": "Route 1",
  "note": "",
  "objects": [
    {
      "id": "back-to-town",
      "name": "To town",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {},
          "once": false,
          "props": {
            "dir": "down",
            "fade": true,
            "look": null,
            "sound": null,
            "to": {
              "dir": "up",
              "map": "town",
              "x": 12,
              "y": 16
            }
          },
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "warp",
      "x": 9,
      "y": 0
    },
    {
      "id": "trainer",
      "name": "Hiker",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "left",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "You two look new out here.",
                "who": "Hiker"
              },
              {
                "cancel": "none",
                "options": [
                  {
                    "text": "Yes please",
                    "then": [
                      {
                        "args": [
                          {
                            "name": "n",
                            "value": 3
                          }
                        ],
                        "script": "give-balls",
                        "t": "call"
                      },
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "Go on, the tall grass is full of friends.",
                        "who": "Hiker"
                      }
                    ],
                    "when": null
                  },
                  {
                    "text": "We are fine",
                    "then": [
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "Suit yourselves!",
                        "who": "Hiker"
                      }
                    ],
                    "when": null
                  }
                ],
                "prompt": "Want a few spare Poké Balls?",
                "t": "choice"
              }
            ]
          },
          "once": true,
          "props": {},
          "sprite": "trainer",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "npc",
      "x": 11,
      "y": 9
    },
    {
      "id": "golden-berry",
      "name": "Golden Berry",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {},
          "once": false,
          "props": {
            "count": 1,
            "item": "golden-berry",
            "look": "pokeball-item"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "item",
      "x": 5,
      "y": 17
    },
    {
      "id": "grass-watcher",
      "name": "Grass watcher",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {
            "step": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Something rustles in the tall grass.",
                "who": ""
              },
              {
                "kind": "?",
                "t": "balloon",
                "target": "p1",
                "wait": false
              }
            ]
          },
          "once": true,
          "props": {},
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "trigger",
      "x": 6,
      "y": 6
    },
    {
      "id": "gate",
      "name": "Old gate",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "up",
          "dirFix": false,
          "layer": "same",
          "needsBoth": true,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "The gate is heavy.",
                "who": ""
              },
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Together, you push it open.",
                "who": ""
              },
              {
                "max": 6,
                "min": 1,
                "name": "gateOpen",
                "op": "set",
                "t": "setVar",
                "value": true,
                "var": null
              },
              {
                "id": "sparkle",
                "t": "sound",
                "volume": 1
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "man",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "npc",
      "x": 9,
      "y": 22
    }
  ],
  "props": {},
  "width": 20
}
);
