// Peachfall (map) — Kit content file, generated by KIT.project.exportFiles (hand edits are fine; keep it valid JSON inside).
// kind: map  project: demo  id: town
// project.js registers KIT.content.projects["demo"]; each maps/<id>.js registers KIT.content.maps["demo"][<id>].
// KIT.project.fromContent("demo") assembles the project again; KIT.project.importFiles({ path: text }) parses the texts.
(function (root, data) {
  var KIT = root.KIT = root.KIT || {};
  var content = KIT.content = KIT.content || {};
  var maps = content.maps = content.maps || {};
  (maps["demo"] = maps["demo"] || {})["town"] = data;
})(typeof window !== 'undefined' ? window : globalThis,
{
  "collision": [
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
  ],
  "height": 18,
  "id": "town",
  "kind": "outdoor",
  "layers": {
    "above": [
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "deco": [
      null, null, null, null, null, null, null, null, null, null, "roof-red", "roof-red", "roof-red", "roof-red", "roof-red", null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, "roof-red-eave", "roof-red-eave", "roof-red-eave", "roof-red-eave", "roof-red-eave", null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, "wall", "wall-window", "wall", "wall-window", "wall", null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, "wall", "wall", "door", "wall", "wall", "roof-blue", "roof-blue", "roof-blue", "roof-blue", "roof-blue", "roof-blue", "roof-blue", null, null,
      null, null, null, "roof-blue", "roof-blue", "roof-blue", "roof-blue", "roof-blue", null, null, null, null, null, null, null, "roof-blue-eave", "roof-blue-eave", "roof-blue-eave", "roof-blue-eave", "roof-blue-eave", "roof-blue-eave", "roof-blue-eave", null, null,
      null, null, null, "roof-blue-eave", "roof-blue-eave", "roof-blue-eave", "roof-blue-eave", "roof-blue-eave", null, null, null, null, null, null, null, "lab-wall", "lab-window", "lab-wall", "lab-window", "lab-wall", "tree-tl", "tree-tr", null, null,
      null, null, null, "wall", "wall-window", "wall", "wall-window", "wall", null, null, null, null, null, null, null, "lab-wall", "lab-wall", "lab-wall", "lab-door", "lab-wall", "tree-bl", "tree-br", null, null,
      null, null, null, "wall", "wall", "door", "wall", "wall", null, null, null, null, null, null, "lamp-post", null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, "mailbox", null, null, "sign", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, "tree-tl", "tree-tr", null, null, null, null, null, null, null, null, null, null, null, null, null, "bench", null, null, null, null, null, null, null,
      null, "tree-bl", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", "fence-h", null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, "flowers-red", null, null, "flowers-yellow", null, null, null, null, null, null, null, null, null, null, "water", "water", "water", null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "flowers-yellow", null, null, "water", "water-lily", "water", null, null, null,
      null, null, null, null, null, null, "tree-tl", "tree-tr", null, null, null, null, null, null, null, null, null, null, "water", "water", "water", null, null, null,
      null, null, null, "flowers-red", null, null, "tree-bl", "tree-br", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, "flowers-yellow", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null
    ],
    "ground": [
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass-2", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass-2", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "path", "path", "path", "path", "path", "path", "path", "path-edge-w", "path", "path-edge-e", "path", "path", "path", "path", "path", "path", "path", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass-2", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass-2", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass",
      "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "path-edge-w", "path", "path-edge-e", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass", "grass"
    ],
    "regions": [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ],
    "terrain": [
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    ]
  },
  "music": "town",
  "name": "Peachfall",
  "note": "",
  "objects": [
    {
      "id": "home-door",
      "name": "Home",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {},
          "once": false,
          "props": {
            "dir": "down",
            "fade": true,
            "look": null,
            "sound": null,
            "to": {
              "dir": "up",
              "map": "home",
              "x": 5,
              "y": 8
            }
          },
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "warp",
      "x": 12,
      "y": 3
    },
    {
      "id": "lab-door",
      "name": "Lab",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {},
          "once": false,
          "props": {
            "dir": "down",
            "fade": true,
            "look": null,
            "sound": null,
            "to": {
              "dir": "up",
              "map": "lab",
              "x": 7,
              "y": 8
            }
          },
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "warp",
      "x": 18,
      "y": 6
    },
    {
      "id": "town-sign",
      "name": "Sign",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "PEACHFALL — small town, big sky.",
                "who": ""
              }
            ]
          },
          "once": false,
          "props": {
            "look": "sign"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "sign",
      "x": 8,
      "y": 9
    },
    {
      "id": "grandma",
      "name": "Grandma",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "look",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Everyone is a beginner once, dear.",
                "who": "Grandma"
              },
              {
                "cancel": "none",
                "options": [
                  {
                    "text": "Yes",
                    "then": [
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "{pause} That is nice.",
                        "who": "Grandma"
                      },
                      {
                        "max": 6,
                        "min": 1,
                        "name": "friendship",
                        "op": "add",
                        "t": "setVar",
                        "value": 1,
                        "var": null
                      }
                    ],
                    "when": null
                  },
                  {
                    "text": "Maybe later",
                    "then": [
                      {
                        "bg": "window",
                        "face": null,
                        "position": "bottom",
                        "t": "say",
                        "text": "Off you go, then.",
                        "who": "Grandma"
                      }
                    ],
                    "when": null
                  }
                ],
                "prompt": "Sit with her a while?",
                "t": "choice"
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "grandma",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "npc",
      "x": 16,
      "y": 9
    },
    {
      "id": "kid",
      "name": "Kid",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 4,
            "kind": "wander",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "My Pokémon walks behind me! {pause} Yours can too.",
                "who": "Kid"
              }
            ]
          },
          "once": false,
          "props": {},
          "sprite": "kid-boy",
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "npc",
      "x": 5,
      "y": 13
    },
    {
      "id": "chapter-card",
      "name": "Chapter card",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "below",
          "needsBoth": false,
          "on": {
            "step": [
              {
                "ms": 2000,
                "subtitle": "A New Morning",
                "t": "chapter",
                "title": "Chapter One"
              }
            ]
          },
          "once": true,
          "props": {},
          "sprite": null,
          "stepAnim": false,
          "through": true,
          "visible": false,
          "when": null
        }
      ],
      "type": "trigger",
      "x": 12,
      "y": 4
    },
    {
      "id": "garden-sign",
      "name": "Garden sign",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "THE GARDEN — everyone you have befriended lives here.",
                "who": ""
              },
              {
                "bg": "window",
                "face": null,
                "position": "bottom",
                "t": "say",
                "text": "Walk up to one of them to say hello.",
                "who": ""
              }
            ]
          },
          "once": false,
          "props": {
            "look": "sign"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "sign",
      "x": 10,
      "y": 11
    },
    {
      "id": "job-board",
      "name": "Job board",
      "note": "",
      "pages": [
        {
          "behaviour": {
            "frequency": 2,
            "kind": "none",
            "radius": 3,
            "repeat": true,
            "route": [],
            "speed": 1
          },
          "dir": "down",
          "dirFix": false,
          "layer": "same",
          "needsBoth": false,
          "on": {
            "interact": [
              {
                "board": "",
                "t": "openJobBoard"
              }
            ]
          },
          "once": false,
          "props": {
            "jobs": [
              {
                "count": 2,
                "desc": "The hedge by the pond is heavy with them.",
                "flag": null,
                "id": "berries",
                "minutes": 45,
                "needs": "",
                "repeatable": true,
                "reward": "berry",
                "suits": "grass",
                "title": "Gather berries"
              },
              {
                "count": 1,
                "desc": "Grandma has a letter for the lab.",
                "flag": "postRun",
                "id": "post",
                "minutes": 30,
                "needs": "",
                "repeatable": true,
                "reward": "pokeball",
                "suits": "electric",
                "title": "Run the post"
              },
              {
                "count": 1,
                "desc": "Somebody small is hiding under the bench.",
                "flag": "catFound",
                "id": "lost-cat",
                "minutes": 90,
                "needs": "",
                "repeatable": false,
                "reward": "golden-berry",
                "suits": "",
                "title": "Find the lost cat"
              }
            ],
            "look": "sign",
            "title": "Odd jobs"
          },
          "sprite": null,
          "stepAnim": false,
          "through": false,
          "visible": true,
          "when": null
        }
      ],
      "type": "job-board",
      "x": 14,
      "y": 9
    }
  ],
  "props": {
    "garden": {
      "region": 3
    }
  },
  "width": 24
}
);
