// Nature + cave tiles (16×16, GBA-era palette). '.' = transparent.
// Ground tiles (grass, path, sand, water, cave-floor, cave-wall) tile seamlessly;
// objects (rock, trees, bush, stump, log, bridges, cave-rock) have transparent
// backgrounds so they can sit on the deco layer over any ground.
PKMN.TILES.register([
  { id: 'grass', name: 'Grass', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838' },
    rows: [
      'gggggggggggggggg',
      'gggggggggggGgggg',
      'ggGgggggggggGggg',
      'gggGgggggggggggg',
      'gggggggggggggggg',
      'ggggggggGggggggg',
      'gGgggggggGgggggg',
      'ggGggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggGgg',
      'ggggGgggggggggGg',
      'gggggGgggggggggg',
      'gggggggggggggggg',
      'ggggggggggGggggg',
      'gGgggggggggGgggg',
      'ggGggggggggggggg',
    ] },

  { id: 'grass-2', name: 'Grass (tufts)', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838', d: '#48983c' },
    rows: [
      'gggggggggggggggg',
      'ggggggggggggGggg',
      'gggggggggggggGgg',
      'ggGgGgGggggggggg',
      'gggGdGgggggggggg',
      'ggggdggggggggggg',
      'gggggggggggggggg',
      'gGgggggggggggggg',
      'ggGggggggggggggg',
      'gggggggggGgGgGgg',
      'ggggggggggGdGggg',
      'gggggggggggdgggg',
      'gggggggggggggggg',
      'gggGgggggggggggg',
      'ggggGgggggggggGg',
      'gggggggggggggggg',
    ] },

  { id: 'tall-grass', name: 'Tall grass', group: 'nature', solid: false, encounter: true,
    palette: { g: '#78c850', G: '#58a838', d: '#48983c' },
    rows: [
      'GggGggGgGggGggGg',
      'GggGggGgGggGggGg',
      'GGgGgGGgGGgGgGGg',
      'gGdGdGgggGdGdGgg',
      'ggdddgggggdddggg',
      'ggGgGggGggGgGggG',
      'ggGgGggGggGgGggG',
      'gGGgGGgGgGGgGGgG',
      'dGgggGdGdGgggGdG',
      'dgggggdddgggggdd',
      'gggggggggggggggg',
      'GggGggGgGggGggGg',
      'GggGggGgGggGggGg',
      'GGgGgGGgGGgGgGGg',
      'gGdGdGgggGdGdGgg',
      'ggdddgggggdddggg',
    ] },

  { id: 'flowers-red', name: 'Red flowers', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838', c: '#f05858', y: '#f8e878' },
    rows: [
      'gggggggggggggggg',
      'gggcgggggggggggg',
      'ggcycggggggcgggg',
      'gggcGgggggcycggg',
      'gggggggggggcGggg',
      'gggggggggggggggg',
      'gGgggggggggggggg',
      'ggGggggggggggggg',
      'ggggggcggggggggg',
      'gggggcycgggggggg',
      'ggggggcGgggggcgg',
      'ggggggggggggcycg',
      'gggggggggGgggcGg',
      'gggGggggggGggggg',
      'ggggGggggggggggg',
      'gggggggggggggggg',
    ] },

  { id: 'flowers-yellow', name: 'Yellow flowers', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838', c: '#f8d840', y: '#f89030' },
    rows: [
      'gggggggggggggggg',
      'gggcgggggggggggg',
      'ggcycggggggcgggg',
      'gggcGgggggcycggg',
      'gggggggggggcGggg',
      'gggggggggggggggg',
      'gGgggggggggggggg',
      'ggGggggggggggggg',
      'ggggggcggggggggg',
      'gggggcycgggggggg',
      'ggggggcGgggggcgg',
      'ggggggggggggcycg',
      'gggggggggGgggcGg',
      'gggGggggggGggggg',
      'ggggGggggggggggg',
      'gggggggggggggggg',
    ] },

  { id: 'flowers-blue', name: 'Blue flowers', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838', c: '#5898f8', y: '#f8f0a0' },
    rows: [
      'gggggggggggggggg',
      'gggcgggggggggggg',
      'ggcycggggggcgggg',
      'gggcGgggggcycggg',
      'gggggggggggcGggg',
      'gggggggggggggggg',
      'gGgggggggggggggg',
      'ggGggggggggggggg',
      'ggggggcggggggggg',
      'gggggcycgggggggg',
      'ggggggcGgggggcgg',
      'ggggggggggggcycg',
      'gggggggggGgggcGg',
      'gggGggggggGggggg',
      'ggggGggggggggggg',
      'gggggggggggggggg',
    ] },

  { id: 'path', name: 'Path', group: 'nature', solid: false,
    palette: { p: '#d8b878', P: '#c09858', q: '#e8cc98' },
    rows: [
      'pppppppppppppppp',
      'pppPPppppppppppp',
      'ppppppppppppPPpp',
      'ppppppqppppppppp',
      'ppppppppPPpppppp',
      'pPpppppppppppppp',
      'ppppppppppppqppp',
      'ppppppPPpppppppp',
      'pppppppppppppPpp',
      'ppPPpppppppppppp',
      'ppqppppppppppppp',
      'ppppppppppPPpppp',
      'ppppPppppppppppp',
      'pppppppppqpppppp',
      'pppppppPPppppppp',
      'ppppppppppppppPp',
    ] },

  { id: 'path-edge-n', name: 'Path edge (grass N)', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838', p: '#d8b878', P: '#c09858', q: '#e8cc98' },
    rows: [
      'gggggggggggggggg',
      'ggGggggggggGgggg',
      'gggGgggggggggggg',
      'gggggggggggggggg',
      'GGggggGGGGggggGG',
      'ppGGGGppppGGGGpp',
      'pppppppppppppppp',
      'ppppPPpppppppppp',
      'pppppppppppPpppp',
      'pPpppppppppppppp',
      'ppppppppPPpppppp',
      'pppppppppppppppp',
      'pppPpppppppppqpp',
      'ppppppppppppPPpp',
      'ppppppPppppppppp',
      'pppppppppppppppp',
    ] },

  { id: 'path-edge-s', name: 'Path edge (grass S)', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838', p: '#d8b878', P: '#c09858', q: '#e8cc98' },
    rows: [
      'pppppppppppppppp',
      'ppppppPppppppppp',
      'ppppppppppppPPpp',
      'pppPpppppppppqpp',
      'pppppppppppppppp',
      'ppppppppPPpppppp',
      'pPpppppppppppppp',
      'pppppppppppPpppp',
      'ppppPPpppppppppp',
      'pppppppppppppppp',
      'ppGGGGppppGGGGpp',
      'GGggggGGGGggggGG',
      'gggggggggggggggg',
      'gggGgggggggggggg',
      'ggGggggggggGgggg',
      'gggggggggggggggg',
    ] },

  { id: 'path-edge-e', name: 'Path edge (grass E)', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838', p: '#d8b878', P: '#c09858', q: '#e8cc98' },
    rows: [
      'pppppppppppGgggg',
      'pppPPppppppGgggg',
      'ppppppppppGggggg',
      'ppppppppppGggGgg',
      'ppppPPppppGgggGg',
      'ppppppppppGggggg',
      'pPpppppppppGgggg',
      'pppppppppppGgggg',
      'pppppppPPppGgggg',
      'pppppppppppGgGgg',
      'ppqpppppppGgggGg',
      'ppppppppppGggggg',
      'ppppPpppppGggggg',
      'ppppppppppGggggg',
      'pppppppPpppGgggg',
      'pppppppppppGgggg',
    ] },

  { id: 'path-edge-w', name: 'Path edge (grass W)', group: 'nature', solid: false,
    palette: { g: '#78c850', G: '#58a838', p: '#d8b878', P: '#c09858', q: '#e8cc98' },
    rows: [
      'ggggGppppppppppp',
      'ggggGpppppppPPpp',
      'gggggGpppppppppp',
      'gGgggGpppppppppp',
      'ggGggGppppPPpppp',
      'gggggGpppppppppp',
      'ggggGppppppppppp',
      'ggggGppppPPppppp',
      'ggggGppppppppppp',
      'ggggGpppppppppPp',
      'gggggGpppppppppp',
      'gGgggGppppppqppp',
      'ggGggGpppPpppppp',
      'gggggGpppppppppp',
      'ggggGppppppppppp',
      'ggggGpppppPPpppp',
    ] },

  { id: 'sand', name: 'Sand', group: 'nature', solid: false,
    palette: { s: '#f0e0a8', S: '#e0c888', t: '#f8f0c8' },
    rows: [
      'ssssssssssssssss',
      'sssSSsssssssssss',
      'ssssssssssssSSss',
      'sssssstsssssssss',
      'ssssssssSSssssss',
      'sSssssssssssssss',
      'sssssssssssstsss',
      'ssssssSSssssssss',
      'sssssssssssssSss',
      'ssSSssssssssssss',
      'sstsssssssssssss',
      'ssssssssssSSssss',
      'ssssSsssssssssss',
      'ssssssssstssssss',
      'sssssssSSsssssss',
      'ssssssssssssssSs',
    ] },

  { id: 'water', name: 'Water', group: 'nature', solid: true,
    palette: { w: '#4890f0', W: '#78b8f8', v: '#3878d8' },
    frames: [ [
      'wwwwwwwwwwwwwwww',
      'wwWWWwwwwwwwwwww',
      'wwwwwwwvvwwwwwww',
      'wwwwwwwwwwWWWwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwvv',
      'wwwwWWWwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwvvwwwwwwwwwwww',
      'wwwwwwwwwwwwWWWw',
      'wwwwwwwwwwwwwwww',
      'wWWWwwwwwwvvwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwWWWwwwww',
      'wwwwwvvwwwwwwwww',
      'wwwwwwwwwwwwwwww',
    ], [
      'wwwwwwwwwwwwwwww',
      'wwwWWWwwwwwwwwww',
      'wwwwwwvvwwwwwwww',
      'wwwwwwwwwwwWWWww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwvvw',
      'wwwwwWWWwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wvvwwwwwwwwwwwww',
      'wwwwwwwwwwwwwWWW',
      'wwwwwwwwwwwwwwww',
      'wwWWWwwwwvvwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwWWWwwww',
      'wwwwvvwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
    ] ] },

  { id: 'water-lily', name: 'Water (lily pad)', group: 'nature', solid: true,
    palette: { w: '#4890f0', W: '#78b8f8', v: '#3878d8', L: '#78d058', l: '#50b040', j: '#308830', f: '#f890c0', F: '#fff0f8' },
    frames: [ [
      'wwwwwwwwwwwwwwww',
      'wwWWWwwwwwwwwwww',
      'wwwwwwwvvwwwwwww',
      'wwwwwfwwwwWWWwww',
      'wwwwfFfjjjwwwwww',
      'wwwwwfLLLLjwwwvv',
      'wwwwjLLLLLljwwww',
      'wwwwjLLLLlljwwww',
      'wwvvjLLljwwwwwww',
      'wwwwjLllllljWWWw',
      'wwwwjlllllljwwww',
      'wWWWwjlllljvwwww',
      'wwwwwwjjjjwwwwww',
      'wwwwwwwwWWWwwwww',
      'wwwwwvvwwwwwwwww',
      'wwwwwwwwwwwwwwww',
    ], [
      'wwwwwwwwwwwwwwww',
      'wwwWWWwwwwwwwwww',
      'wwwwwwvvwwwwwwww',
      'wwwwwfwwwwwWWWww',
      'wwwwfFfjjjwwwwww',
      'wwwwwfLLLLjwwvvw',
      'wwwwjLLLLLljwwww',
      'wwwwjLLLLlljwwww',
      'wvvwjLLljwwwwwww',
      'wwwwjLllllljwWWW',
      'wwwwjlllllljwwww',
      'wwWWWjlllljwwwww',
      'wwwwwwjjjjwwwwww',
      'wwwwwwwwwWWWwwww',
      'wwwwvvwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
    ] ] },

  { id: 'rock', name: 'Rock', group: 'nature', solid: true,
    palette: { x: '#c8c8d0', r: '#a0a0a8', R: '#707880', k: '#505058' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.....kkkkk......',
      '....kxxxrrk.....',
      '...kxxxrrrrk....',
      '...kxxrrrrRRk...',
      '...kxrrrrRRRk...',
      '...krrrRRRRRk...',
      '....kRRRRRRk....',
      '.....kkkkkk.....',
      '................',
      '................',
      '................',
    ] },

  { id: 'boulder', name: 'Boulder', group: 'nature', solid: true,
    palette: { x: '#c8c8d0', r: '#a0a0a8', R: '#707880', k: '#505058' },
    rows: [
      '................',
      '................',
      '.....kkkkkk.....',
      '...kkxxxxrrkk...',
      '..kxxxxxrrrrRk..',
      '.kxxxxxrrrrrRRk.',
      '.kxxxxrrrrrrRRk.',
      '.kxxxrrrrrrrRRk.',
      '.kxxrrrrrrrRRRk.',
      '.kxrrrrrrrRRRRk.',
      '.krrrrrrrRRRRRk.',
      '..krrrrrRRRRRk..',
      '...krrrRRRRRk...',
      '....kkkkkkkk....',
      '................',
      '................',
    ] },

  { id: 'tree-small', name: 'Small tree', group: 'nature', solid: true,
    palette: { e: '#78d068', t: '#48a848', T: '#308838', O: '#205828', b: '#b88050', B: '#906038', o: '#604028' },
    rows: [
      '.....OOOOOO.....',
      '...OOeeeetttOO..',
      '..OeeeeetttttO..',
      '.OeeeeettttttTO.',
      '.OeeeettttttTTO.',
      '.OeeetttttttTTO.',
      '.OeettttttttTTO.',
      '.OetttttttTTTTO.',
      '.OtttttttTTTTTO.',
      '..OttttTTTTTTO..',
      '...OOTTTTTTOO...',
      '.....OobbBoO....',
      '......obbBo.....',
      '......obbBo.....',
      '......obbBo.....',
      '......ooooo.....',
    ] },

  { id: 'tree-tl', name: 'Big tree (top-left)', group: 'nature', solid: true,
    palette: { e: '#78d068', t: '#48a848', T: '#308838', O: '#205828' },
    rows: [
      '...........OOOOO',
      '........OOOeeeee',
      '......OOeeeeeeee',
      '.....Oeeeeeeeeee',
      '....Oeeeeeeeeeet',
      '...Oeeeeeeeeeett',
      '..Oeeeeeeeeeettt',
      '..Oeeeeeeeeetttt',
      '.Oeeeeeeeeettttt',
      '.Oeeeeeeeetttttt',
      '.Oeeeeeeettttttt',
      '.Oeeeeeetttttttt',
      '.Oeeeeettttttttt',
      '.Oeeeettttttttttt'.slice(0, 16),
      '.Oeeetttttttttttt'.slice(0, 16),
      '.Oeettttttttttttt'.slice(0, 16),
    ] },

  { id: 'tree-tr', name: 'Big tree (top-right)', group: 'nature', solid: true,
    palette: { e: '#78d068', t: '#48a848', T: '#308838', O: '#205828' },
    rows: [
      'OOOOO...........',
      'ettttOOO........',
      'ettttttttOO.....',
      'ttttttttttO.....',
      'tttttttttttO....',
      'ttttttttttttO...',
      'tttttttttttTO...',
      'tttttttttttTO...',
      'ttttttttttttTTO.',
      'ttttttttttttTTO.',
      'tttttttttttTTTO.',
      'tttttttttttTTTO.',
      'ttttttttttTTTTO.',
      'ttttttttttTTTTO.',
      'tttttttttTTTTTO.',
      'tttttttttTTTTTO.',
    ] },

  { id: 'tree-bl', name: 'Big tree (bottom-left)', group: 'nature', solid: true,
    palette: { e: '#78d068', t: '#48a848', T: '#308838', O: '#205828', b: '#b88050', B: '#906038', o: '#604028' },
    rows: [
      '.Oetttttttttttttt'.slice(0, 16),
      '.Otttttttttttttt',
      '..Ottttttttttttt',
      '..Ottttttttttttt',
      '...Otttttttttttt',
      '....Otttttttttttt'.slice(0, 16),
      '.....Otttttttttt',
      '......OOtttttttt',
      '........OOOtttTT',
      '...........OobbB',
      '............obbB',
      '............obbB',
      '............obbB',
      '............obbB',
      '...........oobbB',
      '...........ooooo',
    ] },

  { id: 'tree-br', name: 'Big tree (bottom-right)', group: 'nature', solid: true,
    palette: { t: '#48a848', T: '#308838', O: '#205828', b: '#b88050', B: '#906038', o: '#604028' },
    rows: [
      'ttttttttTTTTTTO.',
      'ttttttTTTTTTTO..',
      'tttttTTTTTTTO...',
      'ttttTTTTTTTTO...',
      'tttTTTTTTTTO....',
      'ttTTTTTTTTO.....',
      'tTTTTTTTTO......',
      'TTTTTTTTOO......',
      'TTTTTOOO........',
      'BoOO............',
      'Bo..............',
      'Bo..............',
      'Bo..............',
      'Bo..............',
      'Boo.............',
      'oooo............',
    ] },

  { id: 'bush', name: 'Bush', group: 'nature', solid: true,
    palette: { e: '#78d068', t: '#48a848', T: '#308838', O: '#205828' },
    rows: [
      '................',
      '................',
      '................',
      '.....OOOOOO.....',
      '...OOeeeettOO...',
      '..OeeeeetttttO..',
      '.OeeeeettttttTO.',
      '.OeeeettttttTTO.',
      '.OeeetttttttTTO.',
      '.OeettttttttTTO.',
      '.OtttttttTTTTTO.',
      '.OttttttTTTTTTO.',
      '..OttttTTTTTTO..',
      '...OOTTTTTTOO...',
      '.....OOOOOO.....',
      '................',
    ] },

  { id: 'hedge', name: 'Hedge', group: 'nature', solid: true,
    palette: { e: '#78d068', t: '#48a848', T: '#308838', O: '#205828' },
    rows: [
      '.OO..OO..OO..OO.',
      'OeeOOeeOOeeOOeeO',
      'eeeeeeeeeeeeeeee',
      'eeetteeeeeetteee',
      'eeeeeeeeeeeeeeee',
      'tttttttttttttttt',
      'tTTttttttTTttttt',
      'tttttttttttttttt',
      'tttttTTttttttTTt',
      'tttttttttttttttt',
      'tTTttttttTTttttt',
      'TTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTT',
      'OOOOOOOOOOOOOOOO',
      '................',
    ] },

  { id: 'stump', name: 'Stump', group: 'nature', solid: true,
    palette: { c: '#e0b888', b: '#b88050', B: '#906038', o: '#604028' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '.....oooooo.....',
      '...ooccccccoo...',
      '..occcBBBBccco..',
      '..occBccccBcco..',
      '..occcBBBBccco..',
      '..obbbbbbbBBBo..',
      '..obbbbbbbBBBo..',
      '..obbBbbbbBBBo..',
      '..obbbbbbbBBBo..',
      '..oBBBBBBBBBBo..',
      '..oooooooooooo..',
      '................',
    ] },

  { id: 'log', name: 'Log', group: 'nature', solid: true,
    palette: { c: '#e0b888', b: '#b88050', B: '#906038', o: '#604028' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '............ooo.',
      'ooooooooooooccco',
      'obbbbbbbbbboBBBo',
      'obbbbbbbbbboBcBo',
      'obbbbbBbbbboBcBo',
      'oBBBBBBBBBBoBcBo',
      'oBBBBBBBBBBoBBBo',
      'ooooooooooooccco',
      '............ooo.',
      '................',
      '................',
      '................',
    ] },

  { id: 'ledge-down', name: 'Ledge (jump down)', group: 'nature', solid: false, ledge: 'down',
    palette: { g: '#78c850', G: '#58a838', D: '#3c8030', c: '#e8d0a0', C: '#c8a878', d: '#48983c' },
    rows: [
      'gggggggggggggggg',
      'gggggggggggGgggg',
      'ggGgggggggggGggg',
      'gggGgggggggggggg',
      'gggggggggggggggg',
      'ggggggggGggggggg',
      'gGgggggggGgggggg',
      'ggGggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggGgg',
      'ggggGgggggggggGg',
      'DDDDDDDDDDDDDDDD',
      'cccccccccccccccc',
      'ccccCcccccccCccc',
      'CCCCCCCCCCCCCCCC',
      'dddddddddddddddd',
    ] },

  { id: 'bridge-h', name: 'Bridge (horizontal)', group: 'nature', solid: false,
    palette: { c: '#d0a070', b: '#b88050', B: '#906038', o: '#604028' },
    rows: [
      'oooooooooooooooo',
      'cccccccccccccccc',
      'bbbbbbbbbbbbbbbb',
      '.oo.....oo......',
      'oooooooooooooooo',
      'occcocccocccoccc',
      'obbbobbbobbbobbb',
      'obbbobbbobbbobbb',
      'obbbobbbobbbobbb',
      'obbbobbbobbbobbb',
      'oBBBoBBBoBBBoBBB',
      'oooooooooooooooo',
      '.oo.....oo......',
      'cccccccccccccccc',
      'bbbbbbbbbbbbbbbb',
      'oooooooooooooooo',
    ] },

  { id: 'bridge-v', name: 'Bridge (vertical)', group: 'nature', solid: false,
    palette: { c: '#d0a070', b: '#b88050', B: '#906038', o: '#604028' },
    rows: [
      'ocb.oooooooo.cbo',
      'ocbocbbbbbbocbo'.slice(0, 16) ,
      'ocbocbbbbbbocbo'.slice(0, 16) ,
      'ocb.oBBBBBBo.cbo',
      'ocb.oooooooo.cbo',
      'ocb.ocbbbbbo.cbo',
      'ocb.ocbbbbbo.cbo',
      'ocb.oBBBBBBo.cbo',
      'ocb.oooooooo.cbo',
      'ocbocbbbbbbocbo'.slice(0, 16) ,
      'ocbocbbbbbbocbo'.slice(0, 16) ,
      'ocb.oBBBBBBo.cbo',
      'ocb.oooooooo.cbo',
      'ocb.ocbbbbbo.cbo',
      'ocb.ocbbbbbo.cbo',
      'ocb.oBBBBBBo.cbo',
    ] },

  { id: 'cave-floor', name: 'Cave floor', group: 'cave', solid: false,
    palette: { f: '#b0a094', F: '#9c8c80', e: '#c0b0a4' },
    rows: [
      'ffffffffffffffff',
      'fffFFfffffffffff',
      'ffffffffffffFFff',
      'ffffffefffffffff',
      'ffffffffFFffffff',
      'fFffffffffffffff',
      'ffffffffffffefff',
      'ffffffFFffffffff',
      'fffffffffffffFff',
      'ffFFffffffffffff',
      'ffeffffffffffffff'.slice(0, 16),
      'ffffffffffFFffff',
      'ffffFfffffffffff',
      'fffffffffeffffff',
      'fffffffFFfffffff',
      'ffffffffffffffFf',
    ] },

  { id: 'cave-wall', name: 'Cave wall', group: 'cave', solid: true,
    palette: { m: '#8c7464', M: '#a89080', n: '#6c5444', k: '#4c3830' },
    rows: [
      'nnnnnnnnnnnnnnnn',
      'nnkkkkknnnkkkkkn',
      'nkMMMMmknkMMMMmk',
      'nkMMmmmknkMMmmmk',
      'nkMmmmmknkMmmmmk',
      'nkmmmmmknnkkkkkn',
      'nnkkkkknnnnnnnnn',
      'nnnnnnnnnnnnnnnn',
      'kknnnkkkkknnnkkk',
      'MmknkMMMMmknkMMM',
      'mmknkMMmmmknkMMm',
      'mmknkMmmmmknkMmm',
      'mmknkmmmmmknkmmm',
      'kknnkmmmmmknnkkk',
      'nnnnnkkkkknnnnnn',
      'nnnnnnnnnnnnnnnn',
    ] },

  { id: 'cave-rock', name: 'Cave rock', group: 'cave', solid: true,
    palette: { x: '#b8a498', r: '#98847a', R: '#70605a', k: '#4c3c34' },
    rows: [
      '................',
      '................',
      '................',
      '......kkkk......',
      '....kkxxxrkk....',
      '...kxxxxrrrRk...',
      '..kxxxxrrrrRRk..',
      '..kxxxrrrrrRRk..',
      '.kxxxrrrrrrRRRk.',
      '.kxxrrrrrrRRRRk.',
      '.kxrrrrrrRRRRRk.',
      '.krrrrrrRRRRRRk.',
      '..krrrrRRRRRRk..',
      '...kkrrRRRRkk...',
      '.....kkkkkk.....',
      '................',
    ] },
]);
