// Town tiles (16×16). '.' = transparent. GBA / FRLG-style palette.
PKMN.TILES.register([
  { id: 'fence-h', name: 'Fence (horizontal)', group: 'town', solid: true,
    palette: { o: '#604020', w: '#d8a870', m: '#b88050', d: '#906038' },
    rows: [
      '................',
      '...oooooooooo...',
      '...owwwwwwwmo...',
      '...oooooooooo...',
      '.....owwwmo.....',
      'oooooowwwmoooooo',
      'wwwwwowwwmowwwww',
      'mmmmmowwwmommmmm',
      'oooooowwwmoooooo',
      '.....owwwmo.....',
      'oooooowwwmoooooo',
      'wwwwwowwwmowwwww',
      'mmmmmoddddommmmm',
      'oooooooooooooooo',
      '................',
      '................',
    ] },
  { id: 'fence-v', name: 'Fence (vertical)', group: 'town', solid: true,
    palette: { o: '#604020', w: '#d8a870', m: '#b88050', d: '#906038' },
    rows: [
      '..owmo....owmo..',
      '..oooooooooooo..',
      '..oowwwwwwwmoo..',
      '..oooooooooooo..',
      '..owmowwwmowmo..',
      '..owmowwwmowmo..',
      '..owmowwwmowmo..',
      '..owmowwwmowmo..',
      '..owmowwwmowmo..',
      '..owmowwwmowmo..',
      '..owmowwwmowmo..',
      '..owmowwwmowmo..',
      '..owmoddddowmo..',
      '..owmoooooowmo..',
      '..owmo....owmo..',
      '..owmo....owmo..',
    ] },
  { id: 'fence-post', name: 'Fence post', group: 'town', solid: true,
    palette: { o: '#604020', w: '#d8a870', m: '#b88050', d: '#906038' },
    rows: [
      '................',
      '...oooooooooo...',
      '...owwwwwwwmo...',
      '...oooooooooo...',
      '.....owwwmo.....',
      '.....owwwmo.....',
      '.....owwwmo.....',
      '.....owwwmo.....',
      '.....owwwmo.....',
      '.....owwwmo.....',
      '.....owwwmo.....',
      '.....owwwmo.....',
      '.....oddddo.....',
      '.....oooooo.....',
      '................',
      '................',
    ] },
  { id: 'sign', name: 'Sign', group: 'town', solid: true,
    palette: { o: '#604020', w: '#d8a870', m: '#b88050', d: '#906038' },
    rows: [
      '................',
      '.oooooooooooooo.',
      '.owwwwwwwwwwwwo.',
      '.owddddddddwwmo.',
      '.owwwwwwwwwwwmo.',
      '.owdddddddwwwmo.',
      '.owwwwwwwwwwwmo.',
      '.ommmmmmmmmmmmo.',
      '.oooooooooooooo.',
      '......owmo......',
      '......owmo......',
      '......owmo......',
      '......owmo......',
      '......oddo......',
      '......oooo......',
      '................',
    ] },
  { id: 'mailbox', name: 'Mailbox', group: 'town', solid: true,
    palette: { o: '#203868', B: '#88b8f8', b: '#4888d8', n: '#2c5cb0', r: '#e84040', k: '#604020', w: '#d8a870', m: '#b88050', d: '#906038' },
    rows: [
      '................',
      '...oooooo..oooo.',
      '..oBBBBBBo.orro.',
      '.oBBbbbbbboorro.',
      '.oBbbbbbbbooooo.',
      '.oBbnnnnbboo....',
      '.oBbbbbbbboo....',
      '.obbbbbbbbo.....',
      '.onnnnnnnno.....',
      '.oooooooooo.....',
      '.....kwmk.......',
      '.....kwmk.......',
      '.....kwmk.......',
      '.....kwmk.......',
      '.....kddk.......',
      '.....kkkk.......',
    ] },
  { id: 'lamp-post', name: 'Lamp post', group: 'town', solid: true,
    palette: { o: '#304858', Y: '#fff8b8', y: '#f8d850', L: '#b0c0d0', g: '#6c7c8c' },
    rows: [
      '.......oo.......',
      '.....oooooo.....',
      '....oYYYYyyo....',
      '....oYYyyyyo....',
      '....oYyyyyyo....',
      '....oyyyyyyo....',
      '.....oooooo.....',
      '......oLgo......',
      '......oLgo......',
      '......oLgo......',
      '......oLgo......',
      '......oLgo......',
      '......oLgo......',
      '.....oLLggo.....',
      '....oLgggggo....',
      '....oooooooo....',
    ] },
  { id: 'bench', name: 'Bench', group: 'town', solid: true,
    palette: { o: '#604020', w: '#d8a870', m: '#b88050', d: '#906038' },
    rows: [
      '................',
      '.oooooooooooooo.',
      '.owwwwwwwwwwwwo.',
      '.ommmmmmmmmmmmo.',
      '.oooooooooooooo.',
      '..od........do..',
      '..od........do..',
      '.oooooooooooooo.',
      '.owwwwwwwwwwwwo.',
      '.owwwwwwwwwwwwo.',
      '.ommmmmmmmmmmmo.',
      '.oooooooooooooo.',
      '..odo......odo..',
      '..odo......odo..',
      '..ooo......ooo..',
      '................',
    ] },
  { id: 'flower-pot', name: 'Flower pot', group: 'town', solid: true,
    palette: { k: '#2c6c24', g: '#58b848', G: '#3c8c30', r: '#e84040', p: '#f89090', o: '#703820', C: '#e8a070', c: '#d08050', D: '#a05830' },
    rows: [
      '................',
      '....kkk..kkk....',
      '...kprrkkprrk...',
      '...krrrkkrrrk...',
      '..kgkkkggkkkgk..',
      '.kgggggggggggGk.',
      '.kGggggGGgggGGk.',
      '..kGGGGkkGGGGk..',
      '..oooooooooooo..',
      '.oCCCCCCCCCCCCo.',
      '.oDDDDDDDDDDDDo.',
      '..oCCcccccccDo..',
      '..oCcccccccDDo..',
      '...oCccccccDo...',
      '....oDDDDDDo....',
      '....oooooooo....',
    ] },
  { id: 'roof-red', name: 'Red roof', group: 'town', solid: true,
    palette: { L: '#f08078', R: '#e05850', D: '#a83830' },
    rows: [
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
    ] },
  { id: 'roof-red-eave', name: 'Red roof (eave)', group: 'town', solid: true,
    palette: { L: '#f08078', R: '#e05850', D: '#a83830', S: '#702820' },
    rows: [
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'LLLLLLLLLLLLLLLL',
      'DDDDDDDDDDDDDDDD',
      'SSSSSSSSSSSSSSSS',
    ] },
  { id: 'roof-blue', name: 'Blue roof', group: 'town', solid: true,
    palette: { L: '#80a8f0', R: '#4878d8', D: '#3050a0' },
    rows: [
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
    ] },
  { id: 'roof-blue-eave', name: 'Blue roof (eave)', group: 'town', solid: true,
    palette: { L: '#80a8f0', R: '#4878d8', D: '#3050a0', S: '#203068' },
    rows: [
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'LLLLLLLLLLLLLLLL',
      'DDDDDDDDDDDDDDDD',
      'SSSSSSSSSSSSSSSS',
    ] },
  { id: 'roof-green', name: 'Green roof', group: 'town', solid: true,
    palette: { L: '#88d878', R: '#48a848', D: '#348030' },
    rows: [
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
    ] },
  { id: 'roof-green-eave', name: 'Green roof (eave)', group: 'town', solid: true,
    palette: { L: '#88d878', R: '#48a848', D: '#348030', S: '#245820' },
    rows: [
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RDRRRDRRRDRRRDRR',
      'RDRRRDRRRDRRRDRR',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'RRRDRRRDRRRDRRRD',
      'RRRDRRRDRRRDRRRD',
      'DDDDDDDDDDDDDDDD',
      'LLLLLLLLLLLLLLLL',
      'LLLLLLLLLLLLLLLL',
      'DDDDDDDDDDDDDDDD',
      'SSSSSSSSSSSSSSSS',
    ] },
  { id: 'wall', name: 'Wall', group: 'town', solid: true,
    palette: { c: '#f8f0e0', d: '#e4d8c4', k: '#a89878' },
    rows: [
      'cccccccccccccccc',
      'cccccccccccccccc',
      'cccccccccccccccc',
      'cccccccccccccccc',
      'dddddddddddddddd',
      'cccccccccccccccc',
      'cccccccccccccccc',
      'cccccccccccccccc',
      'cccccccccccccccc',
      'dddddddddddddddd',
      'cccccccccccccccc',
      'cccccccccccccccc',
      'cccccccccccccccc',
      'cccccccccccccccc',
      'dddddddddddddddd',
      'kkkkkkkkkkkkkkkk',
    ] },
  { id: 'wall-window', name: 'Wall (window)', group: 'town', solid: true,
    palette: { c: '#f8f0e0', d: '#e4d8c4', k: '#a89878', f: '#7c5838', B: '#c0e4ff', b: '#78b8f8', w: '#fcfcf8', s: '#b8a888' },
    rows: [
      'cccccccccccccccc',
      'cccccccccccccccc',
      'ccccfffffffffccc',
      'ccccfBBbfBBbfccc',
      'ddddfBbbfBbbfddd',
      'ccccfbbbfbbbfccc',
      'ccccfffffffffccc',
      'ccccfBBbfBBbfccc',
      'ccccfBbbfBbbfccc',
      'ddddfbbbfbbbfddd',
      'ccccfffffffffccc',
      'cccwwwwwwwwwwwcc',
      'cccssssssssssscc',
      'cccccccccccccccc',
      'dddddddddddddddd',
      'kkkkkkkkkkkkkkkk',
    ] },
  { id: 'door', name: 'Door', group: 'town', solid: false, warpLook: true,
    palette: { c: '#f8f0e0', d: '#e4d8c4', k: '#a89878', o: '#604020', w: '#d8a870', m: '#b88050', D: '#906038', y: '#f8d848' },
    rows: [
      'cccccccccccccccc',
      'ccccoooooooocccc',
      'ccccowwwwwwocccc',
      'ccccowmmwmmocccc',
      'ddddowmmwmmodddd',
      'ccccowmmwmmocccc',
      'ccccowmmwmmocccc',
      'ccccowmmwmmocccc',
      'ccccowmmwmyocccc',
      'ddddowmmwmmodddd',
      'ccccowmmwmmocccc',
      'ccccowmmwmmocccc',
      'ccccowmmwmmocccc',
      'ccccowmmwmmocccc',
      'ddddoDDDDDDodddd',
      'kkkkoooooooookkkk',
    ] },
  { id: 'lab-wall', name: 'Lab wall', group: 'town', solid: true,
    palette: { g: '#d8dce4', G: '#eef0f4', l: '#b4bcc8', k: '#8c94a4' },
    rows: [
      'GGGGGGGGGGGGGGGG',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'llllllllllllllll',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'llllllllllllllll',
      'kkkkkkkkkkkkkkkk',
    ] },
  { id: 'lab-window', name: 'Lab window', group: 'town', solid: true,
    palette: { g: '#d8dce4', G: '#eef0f4', l: '#b4bcc8', k: '#8c94a4', f: '#506478', B: '#c0e4ff', b: '#78b8f8' },
    rows: [
      'GGGGGGGGGGGGGGGG',
      'gggggggggggggggg',
      'gggggggggggggggg',
      'gffffffffffffffg',
      'gfBBbfBBBbfBBbfg',
      'gfBbbfBBbbfBbbfg',
      'gfbbbfbbbbfbbbfg',
      'lffffffffffffffl',
      'gfBBbfBBBbfBBbfg',
      'gfBbbfBBbbfBbbfg',
      'gfbbbfbbbbfbbbfg',
      'gffffffffffffffg',
      'gllllllllllllllg',
      'gggggggggggggggg',
      'llllllllllllllll',
      'kkkkkkkkkkkkkkkk',
    ] },
  { id: 'lab-door', name: 'Lab door', group: 'town', solid: false, warpLook: true,
    palette: { g: '#d8dce4', G: '#eef0f4', l: '#b4bcc8', k: '#8c94a4', f: '#506478', B: '#c0e4ff', b: '#78b8f8', h: '#f0f4f8' },
    rows: [
      'GGGGGGGGGGGGGGGG',
      'gggffffffffffggg',
      'gggfBBBffBBBfggg',
      'gggfBBbffBBbfggg',
      'gggfBbbffBbbfggg',
      'gggfbbbffbbbfggg',
      'gggfbbbffbbbfggg',
      'lllfbbbffbbbflll',
      'gggfbbhffhbbfggg',
      'gggfbbhffhbbfggg',
      'gggfbbbffbbbfggg',
      'gggfbbbffbbbfggg',
      'gggfbbbffbbbfggg',
      'gggfbbbffbbbfggg',
      'lllfbbbffbbbflll',
      'kkkffffffffffkkk',
    ] },
  { id: 'pokeball-item', name: 'Poké Ball (item)', group: 'town', solid: false,
    palette: { o: '#303038', R: '#e83838', L: '#f88080', W: '#f8f8f8', G: '#c0c0c8' },
    rows: [
      '................',
      '................',
      '................',
      '......oooo......',
      '....ooRRRRoo....',
      '...oRLLRRRRRo...',
      '...oRLRRRRRRo...',
      '..oRRRRRRRRRRo..',
      '..oRRRRooRRRRo..',
      '..oooooWWooooo..',
      '..oWWWoWWoWWWo..',
      '..oWWWWooWWWGo..',
      '...oGWWWWWGGo...',
      '....ooGGGGoo....',
      '......oooo......',
      '................',
    ] },
]);
